Feature add the voting phase
xgeekshq/split pull request #1137
Opened 2023-02-22 11:10 UTC by GoncaloCanteiro

Relates to #1048 

## Screenshots (if visual changes)

![image](https://user-images.githubusercontent.com/58892791/220410289-308b14ad-acf8-48a9-91be-5fa9a19212c7.png)
![image](https://user-images.githubusercontent.com/58892791/220411221-07efc75e-1a3e-4b41-b2dd-cae8c295576f.png)
![image](https://user-images.githubusercontent.com/58892791/220410606-383b8de0-0926-4971-8e09-e1f0663ac847.png)

## Proposed Changes
  - Button to start the voting phase when all sub-boards merged 
  - Alert to confirm that you want to start the voting phase 
  - Add phase attribute as an enum
  
<!--
Mention people who discussed this issue previously

2023-02-22 13:11 UTC, nunocaseiro commented on frontend/src/hooks/useSocketIO.ts
> +      queryClient.invalidateQueries(['board', { id: payload.boardId }]);
Instead of invalidating the query - that makes another request - please use the received payload to update the react query board state directly. 
You can create a method in the `useBoard` hook that updates the board phase in react query cache using the `queryClient.setQueryData`.
 You can check how we are handling these updates on custom hooks

2023-02-22 13:11 UTC, nunocaseiro commented on frontend/src/hooks/useSocketIO.ts
> +      queryClient.invalidateQueries(['board', { id: payload.boardId }]);
You should also add this operation into the queue following the same approach for other received events

2023-02-22 13:12 UTC, nunocaseiro commented on frontend/src/pages/boards/[boardId].tsx
> +      board?.columns[2].cards.length)
```suggestion
    !board?.submitedByUser
```

2023-02-22 15:33 UTC, GoncaloCanteiro commented on frontend/src/pages/boards/[boardId].tsx
> +      board?.columns[2].cards.length)
`(board?.columns[0].cards.length ||
      board?.columns[1].cards.length ||
      board?.columns[2].cards.length)`
If we remove this code the admin can start the voting phase without any cards.

2023-02-23 11:37 UTC, nunocaseiro requested changes

2023-02-23 11:37 UTC, nunocaseiro commented on backend/src/libs/dto/board-phase.dto.ts
> +	phase: string;
```suggestion
	phase: BoardPhases;
```
Sorry, I forgot this

2023-02-23 11:37 UTC, nunocaseiro commented on backend/src/modules/boards/services/update.board.service.ts
> +			boardPhaseDto.phase !== BoardPhases.SUBMITED
```suggestion
			![BoardPhases.ADDCARDS, BoardPhases.VOTINGPHASE, BoardPhases.SUBMITED].includes(
				boardPhaseDto.phase
			)
```

2023-02-23 11:37 UTC, nunocaseiro commented on backend/src/modules/boards/services/update.board.service.ts
> +			await this.boardModel
```suggestion
const { boardId, phase } = boardPhaseDto
			await this.boardModel
```

2023-02-23 11:37 UTC, nunocaseiro commented on backend/src/modules/boards/services/update.board.service.ts
> +						_id: boardPhaseDto.boardId
```suggestion
						_id: boardId
```

2023-02-23 11:37 UTC, nunocaseiro commented on backend/src/modules/boards/services/update.board.service.ts
> +						phase: boardPhaseDto.phase
```suggestion
						phase
```

2023-02-23 11:37 UTC, nunocaseiro commented on frontend/src/hooks/useBoard.tsx
> +    const getBoardQuery = (id: string | undefined) => ['board', { id }];
```suggestion
setReady(false)
    const getBoardQuery = (id: string | undefined) => ['board', { id }];
```

We need this "ready" state to make the socket queue of operations ready to handle the next task. Or on the other hand to lock the queue. 
To make this works you need to add the following line on the top of the file near the other `useState`. 
`const setReady = useSetRecoilState(operationsQueueAtom);`

2023-02-23 11:37 UTC, nunocaseiro commented on frontend/src/hooks/useBoard.tsx
> +    );
```suggestion
    );
    setReady(true)
```

2023-02-23 11:38 UTC, nunocaseiro commented on frontend/src/api/boardService.tsx
> +export const updateBoardPhaseRequest = (board: UpdateBoardPhase): Promise<BoardType> =>
This isn't resolved

2023-02-23 12:16 UTC, GoncaloCanteiro commented on backend/src/modules/boards/services/update.board.service.ts
> +			boardPhaseDto.phase !== BoardPhases.SUBMITED
This validation is done in the Dto, I think it can be removed

2023-02-23 13:04 UTC, nunocaseiro approved these changes
LGTM 🚀 great job

2023-02-23 13:05 UTC, nunocaseiro commented
@all-contributors, please add @GoncaloCanteiro for code

2023-02-23 13:07 UTC, nunocaseiro commented
@all-contributors, please add @GoncaloCanteiro for code

2023-02-23 13:09 UTC, nunocaseiro commented
@all-contributors please add @GoncaloCanteiro  for code

2023-02-23 14:13 UTC, merged