feat: send xgeeks board phase to slack
xgeekshq/split pull request #1156
Opened 2023-02-27 11:56 UTC by GoncaloCanteiro

Relates to #1048 

## Screenshots (if visual changes)
![image](https://user-images.githubusercontent.com/58892791/221553968-23e5d288-16b7-490c-a250-2a77ea64a357.png)
![image](https://user-images.githubusercontent.com/58892791/221554025-46c5f269-36d5-4687-971a-b510d257b1fa.png)

## Proposed Changes

  - Add new service to communication in order to receive SlackChannelId and the message to send
  - Call the service when phase updated

This pull request closes #1048

2023-02-27 16:33 UTC, nunocaseiro requested changes

2023-02-27 16:33 UTC, nunocaseiro commented on backend/src/modules/boards/services/update.board.service.ts
> +			const team = await this.getTeamService.getTeam((board.team as ObjectId).toString());
```suggestion
```

2023-02-27 16:33 UTC, nunocaseiro commented on backend/src/modules/boards/services/update.board.service.ts
>  						_id: boardId
```suggestion
			const {
				slackEnable,
				phase: currentPhase,
				team
			} = await this.boardRepository.updatePhase(boardId, phase)
```
In the `board repository` create a new method that knows how to update the board phase.

```
updatePhase(boardId: string, phase: BoardPhases): Promise<Board> {
		return this.findOneByFieldAndUpdate(
			{
				_id: boardId
			},
			{
				phase
			},
			{ new: true },
			{
				path: 'team',
				select: 'name users -_id'
			}
		);
	}
```

I didn't catch this in the previous pull request but instead of using the `BoardModel`, please use the board repository. The repository should have the responsibility to know how to update the board phase

2023-02-27 16:33 UTC, nunocaseiro commented on backend/src/modules/boards/services/update.board.service.ts
> +				this.configService.getOrThrow(SLACK_ENABLE)
```suggestion
				(team as Team).name === 'xgeeks' &&
				slackEnable === true &&
				currentPhase !== BoardPhases.ADDCARDS &&
				this.configService.getOrThrow(SLACK_ENABLE)
```

2023-02-27 16:33 UTC, nunocaseiro commented on backend/src/modules/boards/services/update.board.service.ts
> +			)} Retro Board \n\n <https://split.kigroup.de/boards/${boardId}> \n\n Take a look and please add your votes. \n\nThank you for your collaboration! :ok_hand: Keep rocking :rocket:`;
```suggestion
			)} retro board \n\n <https://split.kigroup.de/boards/${boardId}> \n\n Take a look and please add your votes. \n\nThank you for your collaboration! :ok_hand: Keep rocking :rocket:`;
```

2023-02-27 16:33 UTC, nunocaseiro commented on backend/src/modules/boards/services/update.board.service.ts
> +			})} Retro Board was submited \n\nThank you for your collaboration! :ok_hand: Keep rocking :rocket:`;
```suggestion
			})} retro board was submited \n\nThank you for your collaboration! :ok_hand: Keep rocking :rocket:`;
```

2023-02-27 16:33 UTC, nunocaseiro commented on backend/src/modules/communication/applications/slack-communication.application.ts
> +
This must be moved to a new application that has the execute method. Each application/use case only handles one main feature. This `communication application` handles the process of slack teams creation

2023-02-27 16:33 UTC, nunocaseiro commented on backend/src/modules/communication/consumers/slack-send-message.consumer.ts
> +		private readonly application: CommunicationApplicationInterface
```suggestion
		private readonly application: PostMessageApplicationInterface
```
or 
```suggestion
		private readonly application: SendMessageApplicationInterface
```

2023-02-27 16:33 UTC, nunocaseiro commented on backend/src/modules/communication/consumers/slack-send-message.consumer.ts
> +		this.application.postMessageOnChannel(job.data);
```suggestion
		this.application.execute(job.data);
```

2023-02-27 16:33 UTC, nunocaseiro commented on backend/src/modules/communication/interfaces/communication.application.interface.ts
> +	postMessageOnChannel(slackMessage: SlackMessageType): Promise<void>;
```suggestion
```

2023-02-28 11:36 UTC, nunocaseiro approved these changes
LGTM 🚀

2023-02-28 11:36 UTC, nunocaseiro commented on backend/src/modules/boards/repositories/board.repository.ts
> +				select: 'name users -_id'
```suggestion
				select: 'name -_id'
```
Do you need the users field? if not you can remove it

2023-02-28 11:37 UTC, GoncaloCanteiro commented on backend/src/modules/boards/repositories/board.repository.ts
> +				select: 'name users -_id'
Yes, it can be removed

2023-02-28 12:53 UTC, nunocaseiro approved these changes

2023-02-28 14:08 UTC, merged