feat: team list refactor and tests
xgeekshq/split pull request #1168
Opened 2023-02-28 16:33 UTC by JoaoSaIvador

Relates to #1165 
Fixes #1165

## Proposed Changes

  - TeamsList component refactor
  - Fixed scrollable component
  - Add tests for TeamsList component

This pull request closes #1165

2023-02-28 21:53 UTC, nunocaseiro requested changes

2023-02-28 21:53 UTC, nunocaseiro commented on frontend/src/components/Teams/TeamsList/TeamItem/index.tsx
>    const isSAdmin = session?.user.isSAdmin;
```suggestion
    const { userId = undefined, isSAdmin = undefined } = { ...session };
```

This is just a suggestion on how we can destructuring an undefined object.
https://stackoverflow.com/questions/48433008/js-es6-destructuring-of-undefined

2023-02-28 21:53 UTC, nunocaseiro submitted a review, later dismissed

2023-03-01 10:26 UTC, StereoPT approved these changes
LGTM  🗝️

2023-03-01 12:48 UTC, merged