refactor: vote repository
xgeekshq/split pull request #1201
Opened 2023-03-07 16:54 UTC by patricia-mdias

Relates to #1183 

## Proposed Changes

  - Add repositories to votes and refactor vote services.

This pull request closes #1183

2023-03-08 10:06 UTC, nunocaseiro requested changes

2023-03-08 10:06 UTC, nunocaseiro commented on backend/src/modules/votes/services/create.vote.service.ts
> +				withSession
same here

2023-03-08 10:06 UTC, nunocaseiro commented on backend/src/modules/votes/services/create.vote.service.ts
> +		);
This should also be in the repository. I mean, the service shouldn't know how to increment the vote count

2023-03-08 10:06 UTC, nunocaseiro commented on backend/src/modules/votes/services/delete.vote.service.ts
> +			withSession
same here this should be moved to the repository. This method is very similar to the one that is used on the create vote file and that should be moved to the repository so it can be reused

2023-03-08 10:06 UTC, nunocaseiro commented on backend/src/modules/votes/services/delete.vote.service.ts
> +		);
This should be moved to a new method in the board repository

2023-03-08 10:06 UTC, nunocaseiro commented on backend/src/modules/votes/services/delete.vote.service.ts
> +			withSession
Same here. The service must not know how to set the votes

2023-03-08 10:20 UTC, patricia-mdias commented on backend/src/modules/votes/interfaces/types.ts
> +		VoteBoardUserRepository: 'VoteBoardUserRepository'
Should I use the update board service, from the votes modules?

2023-03-08 10:42 UTC, nunocaseiro commented on backend/src/modules/votes/interfaces/types.ts
> +		VoteBoardUserRepository: 'VoteBoardUserRepository'
You can but I think you need to have access to the transactions methods from the repository so you can inject the repository in this module if needed

2023-03-09 10:19 UTC, nunocaseiro requested changes

2023-03-09 10:19 UTC, nunocaseiro commented on backend/src/modules/votes/services/delete.vote.service.ts
> +		if (!updatedBoardUser) throw new BadRequestException(UPDATE_FAILED);
same here

2023-03-09 10:19 UTC, nunocaseiro commented on backend/src/modules/votes/services/delete.vote.service.ts
> +				this.removeVotesFromCardGroup(boardId, mappedVotes, cardId, withSession);
```suggestion
				await this.removeVotesFromCardGroup(boardId, mappedVotes, cardId, withSession);
```

2023-03-09 10:19 UTC, nunocaseiro commented on backend/src/modules/votes/services/delete.vote.service.ts
> +			this.removeVotesFromCardItem(boardId, cardItemId, votes, cardId, withSession);
```suggestion
			await this.removeVotesFromCardItem(boardId, cardItemId, votes, cardId, withSession);
```

2023-03-09 10:38 UTC, patricia-mdias commented on backend/src/modules/boards/repositories/board-user.repository.ts
> +	}
No, I will remove it.

2023-03-09 11:20 UTC, patricia-mdias commented on backend/src/modules/votes/services/create.vote.service.ts
> +		if (!updatedBoardUser) throw new BadRequestException(UPDATE_FAILED);
I will create this new module in a new PR since this PR is already long.

2023-03-09 12:00 UTC, merged