refactor: card repository
xgeekshq/split pull request #1204
Opened 2023-03-07 17:52 UTC by CatiaAntunes96

Relates to #1202  #1181 

## Proposed Changes

  - Add card repository
  - Standardisation  of classes and interfaces names of all modules, except votes and comments modules

This pull request closes #1181

2023-03-08 11:05 UTC, nunocaseiro requested changes

2023-03-08 11:05 UTC, nunocaseiro commented on backend/src/modules/teams/controller/team.controller.ts
> +		private createTeamApp: CreateTeamApplication,
```suggestion
		private createTeamApp: CreateTeamApplicationInterface,
```

2023-03-08 11:05 UTC, nunocaseiro commented on backend/src/modules/teams/controller/team.controller.ts
> +		private getTeamApp: GetTeamApplication,
```suggestion
		private getTeamApp: GetTeamApplicationInterface,
```

2023-03-09 10:37 UTC, nunocaseiro requested changes

2023-03-09 10:54 UTC, CatiaAntunes96 commented on backend/src/modules/cards/services/delete.card.service.ts
> +
I added session to all the functions above @nunocaseiro

2023-03-09 11:14 UTC, nunocaseiro approved these changes
LGTM 🚀 gj

2023-03-09 11:15 UTC, merged