test: update phase backend
xgeekshq/split pull request #1222
Opened 2023-03-10 11:44 UTC by GoncaloCanteiro

Relates to:
- #1221 

## Proposed Changes

  - Use new [library](https://www.npmjs.com/package/@golevelup/ts-jest) in order to improve Mocking many dependencies 
  - Refactor board controller 
  - Implement missing tests

This pull request closes:
- #1221

2023-03-10 13:32 UTC, mourabraz reviewed
Looks awesome, I only add some comments as suggestions. 🚀

2023-03-10 13:32 UTC, mourabraz commented on backend/src/modules/boards/services/update.board.service.spec.ts
> +				}
Just a suggestion, you could use a lookup table here:

```js
const table = {
  SLACK_MASTER_CHANNEL_ID: '6405f9a04633b1668f71c068',
  SLACK_ENABLE: true,
  FRONTEND_URL: 'https://split.kigroup.de/'
}

// then
(key: string) => table[key]
```

2023-03-10 13:32 UTC, mourabraz commented on backend/src/modules/boards/services/update.board.service.spec.ts
> +				slackChannelId: expect.stringContaining('6405f9a04633b1668f71c068'),
In this case, I believe that is not a contains assertion. It seems that the value should be exactly the id value.
```js
expect(slackSendMessageServiceMock.execute).toHaveBeenNthCalledWith(1, {
				slackChannelId: '6405f9a04633b1668f71c068', // with the table you can do even better table. SLACK_MASTER_CHANNEL_ID
				message: expect.stringContaining('https://split.kigroup.de/')
			});
```

2023-03-10 13:32 UTC, mourabraz commented on backend/src/modules/communication/applications/slack-send-message-channel.application.spec.ts
> +		const postMessage = jest.spyOn(chatHandler, 'postMessage').mockImplementation(jest.fn());
I would extract this "spyOn" to the "beforeEach" or to "beforeAall" (using it in beforeAll you will need to use the jest.restoreAllMocks()) since it is being used in the next test in the same way

2023-03-10 13:32 UTC, mourabraz commented on backend/src/modules/communication/applications/slack-send-message-channel.application.spec.ts
> +	it('should be called with SlackMessageDto', () => {
Besides my comment above, this test seems very similar to the previous one. It is possible to assert with ToHaveBeenCalledWith only once to check if something was called with the proper argument.

2023-03-10 13:32 UTC, mourabraz commented on backend/src/modules/communication/consumers/slack-send-message.consumer.spec.ts
> +});
I think is missing the tests for "onCompleted", "onFailed", "onError" from the parent class

2023-03-10 13:38 UTC, nunocaseiro requested changes

2023-03-10 13:38 UTC, nunocaseiro commented on backend/src/modules/boards/controller/boards.controller.spec.ts
> +	let updateBoardAppMock: DeepMocked<UpdateBoardApplication>;
```suggestion
	let updateBoardAppMock: DeepMocked<UpdateBoardApplicationInterface>;
```

2023-03-10 13:38 UTC, nunocaseiro commented on backend/src/modules/boards/controller/boards.controller.spec.ts
> +					useValue: createMock<CreateBoardApplication>()
```suggestion
					useValue: createMock<CreateBoardApplicationInterface>()
```

2023-03-10 13:38 UTC, nunocaseiro commented on backend/src/modules/boards/controller/boards.controller.spec.ts
> +					useValue: createMock<GetBoardApplication>()
```suggestion
					useValue: createMock<GetBoardApplicationInterface>()
```

2023-03-10 13:38 UTC, nunocaseiro commented on backend/src/modules/boards/controller/boards.controller.spec.ts
> +					useValue: createMock<UpdateBoardApplication>()
```suggestion
					useValue: createMock<UpdateBoardInterface>()
```

2023-03-10 13:38 UTC, nunocaseiro commented on backend/src/modules/boards/controller/boards.controller.spec.ts
> +					useValue: createMock<DeleteBoardApplication>()
```suggestion
					useValue: createMock<DeleteBoardInterface>()
```

2023-03-10 13:38 UTC, nunocaseiro commented on backend/src/modules/boards/services/update.board.service.spec.ts
> +	let boardRepositoryMock: DeepMocked<BoardRepository>;
```suggestion
	let boardRepositoryMock: DeepMocked<BoardRepositoryInterface>;
```

2023-03-10 13:38 UTC, nunocaseiro commented on backend/src/modules/boards/services/update.board.service.spec.ts
> +					useValue: createMock<SlackCommunicationService>
```suggestion
					useValue: createMock<CommunicationServiceInterface>
```

2023-03-10 13:38 UTC, nunocaseiro commented on backend/src/modules/boards/services/update.board.service.spec.ts
> +					useValue: createMock<SlackSendMessageService>()
```suggestion
					useValue: createMock<SendMessageServiceInterface>()
```

2023-03-10 13:38 UTC, nunocaseiro commented on backend/src/modules/boards/services/update.board.service.spec.ts
> +	let slackSendMessageServiceMock: DeepMocked<SlackSendMessageService>;
```suggestion
	let slackSendMessageServiceMock: DeepMocked<SendMessageServiceInterface>;
```

2023-03-10 13:38 UTC, nunocaseiro commented on backend/src/modules/boards/services/update.board.service.spec.ts
> +					useValue: createMock<GetTeamService>()
```suggestion
					useValue: createMock<GetTeamServiceInterface>()
```

2023-03-10 13:38 UTC, nunocaseiro commented on backend/src/modules/boards/services/update.board.service.spec.ts
> +					useValue: createMock<DeleteCardServiceImpl>()
```suggestion
					useValue: createMock<DeleteCardServiceInterface>()
```

2023-03-10 13:38 UTC, nunocaseiro commented on backend/src/modules/boards/services/update.board.service.spec.ts
> +					useValue: createMock<BoardRepository>()
```suggestion
					useValue: createMock<BoardRepositoryInterface>()
```

2023-03-10 13:38 UTC, nunocaseiro commented on backend/src/modules/boards/services/update.board.service.spec.ts
> +				board as unknown as ReturnType<typeof boardRepositoryMock.updatePhase>
I 
```suggestion
				board 
```

2023-03-10 13:38 UTC, nunocaseiro commented on backend/src/modules/boards/services/update.board.service.spec.ts
> +			});
```suggestion
			const configs = {
				SLACK_MASTER_CHANNEL_ID: '6405f9a04633b1668f71c068',
				SLACK_ENABLE: true,
				FRONTEND_URL: 'https://split.kigroup.de/'
			};
			configServiceMock.getOrThrow.mockImplementation((value: string) => {
				if (value === SLACK_MASTER_CHANNEL_ID) {
					return configs.SLACK_MASTER_CHANNEL_ID;
				}

				if (value === SLACK_ENABLE) {
					return configs.SLACK_ENABLE;
				}

				if (value === FRONTEND_URL) {
					return configs.FRONTEND_URL;
				}
			});

			// Call the service method being tested
			await service.updatePhase(boardPhaseDto);

			// Verify that the slackSendMessageService.execute method with correct data 1 time
			expect(slackSendMessageServiceMock.execute).toHaveBeenNthCalledWith(1, {
				slackChannelId: expect.stringContaining(configs.SLACK_MASTER_CHANNEL_ID),
				message: expect.stringContaining(configs.FRONTEND_URL)
			});
```

2023-03-10 13:38 UTC, nunocaseiro commented on backend/src/modules/communication/applications/slack-send-message-channel.application.spec.ts
> +	it('shoult call postMessage', () => {
```suggestion
	it('should call postMessage', () => {
```

2023-03-10 13:38 UTC, nunocaseiro commented on backend/src/modules/communication/applications/slack-send-message-channel.application.spec.ts
> +	let application: SlackSendMessageApplication;
```suggestion
	let application: SendMessageApplicationInterface;
```

2023-03-10 13:38 UTC, nunocaseiro commented on backend/src/modules/communication/applications/slack-send-message-channel.application.spec.ts
> +		expect(postMessage).toHaveBeenCalledWith('6405f9a04633b1668f71c068', 'SlackMessage');
```suggestion
		expect(postMessage).toHaveBeenCalledWith(
			slackMessageDtoMock.slackChannelId,
			slackMessageDtoMock.message
		);
```

2023-03-10 13:38 UTC, nunocaseiro commented on backend/src/modules/communication/consumers/slack-send-message.consumer.spec.ts
> +	let sendMessageApplicationMock: DeepMocked<SlackSendMessageApplication>;
```suggestion
	let sendMessageApplicationMock: DeepMocked<SendMessageApplicationInterface>;
```

2023-03-10 13:38 UTC, nunocaseiro commented on backend/src/modules/communication/consumers/slack-send-message.consumer.spec.ts
> +					useValue: createMock<SlackSendMessageApplication>()
```suggestion
					useValue: createMock<SendMessageApplicationInterface>()
```

2023-03-10 13:38 UTC, nunocaseiro commented on backend/src/modules/communication/services/slack-send-messages.service.spec.ts
> +	let service: SlackSendMessageService;
```suggestion
	let service: SlackSendMessageServiceInterface;
```

2023-03-10 13:38 UTC, nunocaseiro commented on backend/src/modules/communication/services/slack-send-messages.service.spec.ts
> +		service = module.get<SlackSendMessageService>(SlackSendMessageService);
```suggestion
		service = module.get<SendMessageServiceInterface>(TYPES.services.SlackSendMessageService);
```

2023-03-10 13:43 UTC, nunocaseiro commented on backend/src/modules/boards/applications/update.board.application.spec.ts
> +});
I agree we don't need to test the applications for now. I also agree the logic from the service should be moved to the application / use-case however I think this will be a big refactor. We should estimate the cost/effort by doing that

2023-03-10 17:33 UTC, GoncaloCanteiro commented on backend/src/modules/boards/services/update.board.service.spec.ts
> +	let service: UpdateBoardServiceImpl;
I don't think we should use the `UpdateBoardServiceInterface` as a type because if eventually, we add another interface to the `UpdateBoardService` this test would not work anymore. 
And I'm not sure but I think if we use the Interface we will not have access to the implementation of the methods.

2023-03-10 17:43 UTC, GoncaloCanteiro commented on backend/src/modules/boards/applications/update.board.application.spec.ts
> +	let updateBoardAppMock: UpdateBoardApplication;
As I described before, I don't think we should use the interface for the class that we are testing.

2023-03-13 10:49 UTC, nunocaseiro requested changes

2023-03-13 11:30 UTC, nunocaseiro requested changes

2023-03-13 11:30 UTC, nunocaseiro commented on backend/src/modules/boards/services/update.board.service.spec.ts
> +			board.team = team;
```suggestion
			board.team = TeamFactory.create({ name: 'xgeeks' });
```

I think you don't need to create a new variable

2023-03-13 11:30 UTC, nunocaseiro commented on backend/src/libs/test-utils/mocks/factories/team-factory.mock.ts
> +		_id: faker.datatype.uuid(),
replace the _id value by `faker.database.mongodbObjectId()`

2023-03-13 12:10 UTC, nunocaseiro requested changes

2023-03-13 12:10 UTC, nunocaseiro commented on backend/src/libs/test-utils/mocks/factories/team-factory.mock.ts
> +		_id: faker.datatype.uuid(),
```suggestion
		_id: faker.database.mongodbObjectId(),
```

2023-03-13 14:12 UTC, GoncaloCanteiro commented on backend/src/libs/test-utils/mocks/factories/team-factory.mock.ts
> +		_id: faker.datatype.uuid(),
I think this is already changed, in my code I have mongodbObjectId, and is updated

2023-03-13 14:54 UTC, merged