test: delete board service test
xgeekshq/split pull request #1252
Opened 2023-03-16 09:49 UTC by GoncaloCanteiro

Relates to:
- #1228 

## Proposed Changes

  - Add delete.board.service.spec.ts
  - Add unit tests for the delete method
  - Add unit tests for the deleteBoardsByTeamId method

This pull request closes:
- #1228

2023-03-16 21:07 UTC, nunocaseiro requested changes
GJ here, you have just missed one test for the 40th line

<img width="719" alt="image" src="https://user-images.githubusercontent.com/90208434/225752891-7d79d59b-ed4f-4f8d-b1f9-30a95a13ceb5.png">

2023-03-17 08:31 UTC, mourabraz commented on backend/src/modules/boards/services/delete.board.service.spec.ts
> +			await achiveChannelServiceMock.execute.mockResolvedValue(null);
I believe you should not use "await" after "mockResolvedValue". Does not make sense to return a Promise when you build a mock, this is only an arrangement for when the code being tested runs.

2023-03-17 08:34 UTC, mourabraz commented on backend/src/modules/boards/services/delete.board.service.spec.ts
> +			await deleteBoardUserServiceMock.deleteDividedBoardUsers.mockResolvedValue(2);
The same here. You are building a mock not executing the conde...

2023-03-17 08:35 UTC, mourabraz commented on backend/src/modules/boards/services/delete.board.service.spec.ts
> +			await expect(service.deleteBoardsByTeamId('teamId')).resolves.toBe(true);
and here

2023-03-17 08:35 UTC, mourabraz commented on backend/src/modules/boards/services/delete.board.service.spec.ts
> +			await achiveChannelServiceMock.execute.mockResolvedValue(null);
the same as before

2023-03-17 08:39 UTC, mourabraz commented on backend/src/modules/boards/services/delete.board.service.spec.ts
> +			await achiveChannelServiceMock.execute.mockResolvedValue(null);
same here

2023-03-17 09:23 UTC, GoncaloCanteiro commented on backend/src/modules/boards/services/delete.board.service.spec.ts
> +			await achiveChannelServiceMock.execute.mockResolvedValue(null);
That's a good point, thank you for the tips! 👍

2023-03-17 14:52 UTC, nunocaseiro commented on backend/src/modules/boards/services/delete.board.service.ts
> +			return await this.deleteBoardBoardUsersAndSchedules(boardId, true);
```suggestion
			return this.deleteBoardBoardUsersAndSchedules(boardId, true);
```

2023-03-17 17:11 UTC, nunocaseiro approved these changes
LGTM 🚀 you can wait for Carlo's review

2023-03-17 17:56 UTC, merged