refactor: team pages state logic
xgeekshq/split pull request #1256
Opened 2023-03-16 14:58 UTC by JoaoSaIvador

Relates to:
- #1248 

Fixes:
- #1248 

## Proposed Changes

- Consolidate repeated code into reusable functions or modules
- Create a more structured and modular approach to state management
- Use a consistent naming convention for variables and functions to improve clarity and readability
- Fewer bugs and easier debugging, as there will be less repeated and inconsistent code
- Faster development time, as developers will be able to more easily reuse existing code
- Improved scalability and maintainability, as the updated architecture will be more organized and easier to maintain over time

This pull request closes:
- #1248

2023-03-16 21:39 UTC, nunocaseiro requested changes

2023-03-16 21:39 UTC, nunocaseiro commented on frontend/src/components/Teams/Team/ListMembers/ListMembers.tsx
>    const router = useRouter();
I know you didn't change this line but you can do this:

```suggestion
 const {
    query: { teamId },
  } = useRouter();
```

2023-03-16 21:39 UTC, nunocaseiro commented on frontend/src/components/Teams/TeamsList/TeamItem/TeamItem.tsx
>    const router = useRouter();
```suggestion
  const {pathname} = useRouter();
```

2023-03-16 21:39 UTC, nunocaseiro commented on frontend/src/components/Teams/TeamsList/TeamItem/TeamItem.tsx
> +  const isTeamPage = router.pathname.includes('teams');
```suggestion
  const isTeamPage = pathname.includes('teams');
```

2023-03-16 21:39 UTC, nunocaseiro commented on frontend/src/components/Teams/CreateTeam/CreateTeam.tsx
>    const router = useRouter();
```suggestion
  const {back} = useRouter();
```

2023-03-16 21:39 UTC, nunocaseiro commented on frontend/src/components/Teams/TeamsList/TeamItem/TeamItem.tsx
> +    const queryUserId = router.query.userId;
```suggestion
    const queryUserId = userPathId;
```

2023-03-16 21:39 UTC, nunocaseiro commented on frontend/src/hooks/useTeam.tsx
> +      router.push(ROUTES.Teams);
```suggestion
      push(ROUTES.Teams);
```

2023-03-16 21:39 UTC, nunocaseiro commented on frontend/src/hooks/useTeam.tsx
> +    router,
```suggestion
    router: {push},
```

2023-03-16 21:39 UTC, nunocaseiro commented on frontend/src/pages/teams/[teamId].tsx
> +  const router = useRouter();
```suggestion
  const { replace } = useRouter();
```

2023-03-16 21:39 UTC, nunocaseiro commented on frontend/src/pages/teams/[teamId].tsx
> +    router.replace(ROUTES.Teams);
```suggestion
    replace(ROUTES.Teams);
```

2023-03-17 09:09 UTC, JoaoSaIvador commented on frontend/src/components/Teams/TeamsList/TeamItem/TeamItem.tsx
>    const router = useRouter();
In this file, there's another use of the router and it's inside a useMemo (line 37), so I don't think the destructuring would help much in this case.

``` const router = useRouter();
  const isTeamPage = router.pathname.includes('teams');

  const { deleteTeam, deleteTeamUser } = useTeam();

  const userFound = useMemo(() => {
    const queryUserId = router.query.userId;
    const teamUserId = !isTeamPage && queryUserId ? queryUserId : userId;

    return teamUsers.find((teamUser) => String(teamUser.user?._id) === String(teamUserId));
  }, [router, userId, teamUsers]);

2023-03-17 14:51 UTC, nunocaseiro approved these changes
LGTM 🚀

2023-03-17 15:06 UTC, merged