Test/communication applications tests
xgeekshq/split pull request #1258
Opened 2023-03-16 17:42 UTC by GoncaloCanteiro

Relates to:
- #1255 

## Proposed Changes

  -Add tests to communication applications

This pull request closes:
- #1255

2023-03-16 21:46 UTC, nunocaseiro requested changes
GJ here! You just missed some lines. If you think there is a line that doesn't make sense to test or the tests don't return value please leave a comment with your opinion
<img width="793" alt="image" src="https://user-images.githubusercontent.com/90208434/225759538-f5c4bd03-2f24-400a-9743-0134d4929a87.png">

2023-03-16 21:46 UTC, nunocaseiro commented on backend/src/modules/communication/applications/slack-add-user-channel.application.ts
> +		return await this.inviteMemberToMainChannel(email);
```suggestion
		return this.inviteMemberToMainChannel(email);
```

2023-03-16 21:46 UTC, nunocaseiro commented on backend/src/modules/communication/applications/slack-add-user-channel.application.ts
> +	public async execute(email: string): Promise<boolean> {
```suggestion
	public execute(email: string): Promise<boolean> {
```

2023-03-17 08:13 UTC, mourabraz commented on backend/src/modules/communication/applications/slack-add-user-channel.application.spec.ts
> +			.mockImplementation(jest.fn())
Hi! I am not sure, but it is necessary "mock implementation" and then the "mockReturnValue", I believe you only need mockReturnValue...

2023-03-17 08:20 UTC, mourabraz commented on backend/src/modules/communication/applications/slack-responsible.application.spec.ts
> +		userHandlerMock.mockResolvedValue('newResponsibleId');
The same as before, but in this case, it was split between "beforeAll" and "beforeEach"...
Since its behavior is not been changed you could do this in the "beforeAll" and remove the "mockImplementation" (line48)

2023-03-17 15:14 UTC, nunocaseiro submitted a review, later dismissed
LGMT :rocket:

2023-03-20 12:40 UTC, nunocaseiro approved these changes
LGTM 🚀

2023-03-20 12:41 UTC, merged