1257 refactor user components
xgeekshq/split pull request #1272
Opened 2023-03-20 15:29 UTC by StereoPT

Relates to:
- #1257 

Fixes:
- #1257

## Proposed Changes

  - Refactored the components used in the User Pages

This pull request closes #1257

2023-03-20 17:37 UTC, JoaoSaIvador commented
This pull request also closes the issue #1119

2023-03-20 18:46 UTC, nunocaseiro requested changes

2023-03-20 18:46 UTC, nunocaseiro commented on frontend/src/components/Primitives/Badge/Badge.tsx
> +        borderRadius: '50rem',
```suggestion
        borderRadius: '$800',
```

I'm not sure about this but 50 * 16 = 800

2023-03-20 18:46 UTC, nunocaseiro commented on frontend/src/components/Users/User/Header/Header.spec.tsx
> +    // Arrange
```suggestion
```

2023-03-20 18:46 UTC, nunocaseiro commented on frontend/src/components/Users/UsersList/UserItem/UserItemActions/UserItemActions.tsx
> +    deleteUser: { mutate },
```suggestion
    deleteUser: { mutate: deleteUserMutation },
```

2023-03-20 18:46 UTC, nunocaseiro commented on frontend/src/components/Users/UsersList/UserItem/UserItemActions/UserItemActions.tsx
> +    updateUserIsAdmin: { mutateAsync },
```suggestion
    updateUserIsAdmin: { updateUserMutation },
```

2023-03-20 18:46 UTC, nunocaseiro commented on frontend/src/components/Users/UsersList/UserItem/UserItemActions/UserItemActions.tsx
> +      await mutateAsync(updateTeamUser);
```suggestion
      await updateUserMutation(updateTeamUser);
```

2023-03-20 18:46 UTC, nunocaseiro commented on frontend/src/components/Users/UsersList/UserItem/UserItemActions/UserItemActions.tsx
> +    mutate({ id: user._id });
```suggestion
    deleteUserMutation({ id: user._id });
```

2023-03-21 11:37 UTC, nunocaseiro approved these changes

2023-03-21 17:31 UTC, merged