Refactor/delete card service to usecase
xgeekshq/split pull request #1351
Opened 2023-04-04 15:08 UTC by GoncaloCanteiro

Relates to:
- #1313

## Proposed Changes

  - Refactor delete card service to use case
  - Change deleteCardVotesFromColumn from delete.card.service to delete.vote.service
  -  Implement bulkWrite to prevent multiple calls to the DB. Only do one operation when removing the card votes
  -  Implement tests for the new useCases
  - change MongoGenericRepository type to document

This pull request closes #1313

2023-04-05 12:14 UTC, nunocaseiro requested changes

2023-04-05 12:14 UTC, nunocaseiro commented on backend/src/modules/cards/controller/cards.controller.ts
> +		this.deleteFromCardGroupUseCase.execute({ boardId, cardId, cardItemId });
same as above

2023-04-05 12:14 UTC, nunocaseiro commented on backend/src/modules/cards/controller/cards.controller.ts
>  		this.socketService.sendDeleteCard(deleteCardDto.socketId, deleteCardDto);
```suggestion
const completionHandler = () => {
		this.socketService.sendDeleteCard(deleteCardDto.socketId, deleteCardDto);
}

```
Instead, you can pass a `completionHandler` to the use-case that executes the function passed as an argument at the end of the task. Here in the controller you can `return this.deleteCardUseCase.execute({ boardId, cardId, completionHandler });` and remove the  `async` method prefix. This is already done on the `boards.controller` namely on the getBoard method

2023-04-05 12:14 UTC, nunocaseiro commented on backend/src/modules/columns/services/update.column.service.ts
> +		private deleteVoteService: DeleteVoteServiceInterface
Add `readonly`

2023-04-05 12:14 UTC, nunocaseiro commented on backend/src/modules/votes/services/delete.vote.service.ts
>  	) {}
Add `readonly` please

2023-04-05 12:14 UTC, nunocaseiro commented on backend/src/modules/votes/services/delete.vote.service.ts
> +			if (usersWithVotes.size > 0) {
Use the `isEmpty` method

2023-04-05 12:14 UTC, nunocaseiro commented on backend/src/modules/votes/services/delete.vote.service.ts
> +		if (card.votes?.length) {
Add `isEmpty`

2023-04-05 14:30 UTC, GoncaloCanteiro commented on backend/src/modules/cards/applications/delete-card.use-case.ts
> +		if (getCard.votes?.length) {
Actually, I think this can be removed. The delete-card.use-case is only called when we are removing a single card that isn't included in a group, which means that card.votes will always be empty in this useCase if I'm not mistaken

2023-04-05 14:36 UTC, CatiaBarroco-xgeeks commented on backend/src/modules/cards/applications/delete-from-card-group.use-case.ts
> +					(card.votes.length >= 0 || card.comments.length >= 0)
I think it would be better read if all this logic were contained within one or two constants.

2023-04-05 14:41 UTC, CatiaBarroco-xgeeks commented on backend/src/modules/cards/applications/delete-from-card-group.use-case.ts
> +				if (result.ok !== 1) {
`result.ok !== 1 `is strange, looking at this logic for the first time, maybe putting it inside a constant and explaining what this is supposed to be validating would be interesting for future, who change this file on the future  understand what this logic is validating. what do you think?

2023-04-05 14:50 UTC, GoncaloCanteiro commented on backend/src/modules/cards/applications/delete-card.use-case.ts
> +		if (votesByUsers.size > 0) {
This doesn't work, the votesByUsers is a Map<string,number> and the isEmpty does not recognize that.

2023-04-05 16:26 UTC, GoncaloCanteiro commented on backend/src/modules/votes/services/delete.vote.service.ts
> +			if (usersWithVotes.size > 0) {
As explained above isEmpty does not work in a Map

2023-04-05 16:39 UTC, GoncaloCanteiro commented on backend/src/modules/cards/applications/delete-from-card-group.use-case.ts
> +				if (result.ok !== 1) {
Yes, that is a good point.  Actually, I think this can be replaced with `!result.ok` and it's more understandable.

2023-04-05 16:53 UTC, CatiaBarroco-xgeeks commented on backend/src/modules/cards/applications/delete-from-card-group.use-case.ts
> +				if (result.ok !== 1) {
so this function is for if the result is not "ok"?

2023-04-05 16:55 UTC, CatiaBarroco-xgeeks commented on backend/src/modules/cards/applications/delete-from-card-group.use-case.ts
> +					(card.votes.length >= 0 || card.comments.length >= 0)
Done 5d793b86b0723ddff45633cd12b27f6fd37057eb

2023-04-05 16:58 UTC, CatiaBarroco-xgeeks commented on backend/src/modules/cards/applications/delete-card.use-case.ts
> +				if (result.ok !== 1) {
you have the same here

2023-04-05 16:58 UTC, CatiaBarroco-xgeeks commented on backend/src/modules/votes/services/delete.vote.service.ts
> +			if (result.ok !== 1) {
same

2023-04-05 17:01 UTC, GoncaloCanteiro commented on backend/src/modules/cards/applications/delete-from-card-group.use-case.ts
> +				if (result.ok !== 1) {
the result has a type of BulkWriteResult that give the information if the operation was successful, I can change the name to `!bulkWriteResult.ok` to be more accurate

2023-04-05 17:08 UTC, GoncaloCanteiro commented on backend/src/modules/cards/applications/delete-from-card-group.use-case.ts
> +				if (result.ok !== 1) {
Alright, then I will leave the result 😅

2023-04-05 17:11 UTC, CatiaBarroco-xgeeks commented on backend/src/modules/cards/applications/delete-from-card-group.use-case.ts
> +				if (result.ok !== 1) {
I thik "bulkWriteResult" is not explanatory name for someone who is not familiar with the code to understand. 
I think that's fine, or if you want to put a constant with that like 
`const notSucessfulResult = !result.ok`. but if you don't want it, that's fine, I think it's readable

2023-04-05 17:12 UTC, CatiaBarroco-xgeeks commented on backend/src/modules/votes/services/delete.vote.service.ts
> +			if (result.ok !== 1) {
Done 0f861114742e06a69bfc2df5e77c7ff77cce3274

2023-04-05 17:13 UTC, CatiaBarroco-xgeeks commented on backend/src/modules/cards/applications/delete-card.use-case.ts
> +				if (result.ok !== 1) {
Done 0f861114742e06a69bfc2df5e77c7ff77cce3274

2023-04-05 17:16 UTC, CatiaBarroco-xgeeks commented on backend/src/modules/cards/applications/delete-card.use-case.ts
> +				if (result.ok !== 1) {
Done 1c4bda4606334d5fd28fcfe4d4ad83a64791a50a

2023-04-05 17:16 UTC, CatiaBarroco-xgeeks commented on backend/src/modules/votes/services/delete.vote.service.ts
> +			if (result.ok !== 1) {
Done 1c4bda4606334d5fd28fcfe4d4ad83a64791a50a

2023-04-05 17:16 UTC, CatiaBarroco-xgeeks commented on backend/src/modules/cards/applications/delete-from-card-group.use-case.ts
> +				if (result.ok !== 1) {
Done 1c4bda4606334d5fd28fcfe4d4ad83a64791a50a

2023-04-06 09:41 UTC, nunocaseiro requested changes

2023-04-06 09:41 UTC, nunocaseiro commented on backend/src/modules/cards/controller/cards.controller.ts
>  		return HttpStatus.OK;
```suggestion
		return this.deleteCardUseCase.execute({ boardId, cardId, completionHandler });

```

2023-04-06 09:41 UTC, nunocaseiro commented on backend/src/modules/cards/controller/cards.controller.ts
>  		return HttpStatus.OK;
```suggestion
		return this.deleteFromCardGroupUseCase.execute({ boardId, cardId, cardItemId, completionHandler });

```

2023-04-06 14:21 UTC, merged