feat: add sidebar responsiveness
xgeekshq/split pull request #1376
Opened 2023-04-10 13:58 UTC by juniorboos

Relates to:
- #971

## Screenshots (if visual changes)
<table align="center" border="0" cellpadding="0" cellspacing="0">
  <thead>
    <tr>
      <td>
       Old
      </td>
      <td>
        New
      </td>
    </tr>
  </thead>
<tr>
      <td>
<img width="422" alt="image" src="https://user-images.githubusercontent.com/61988699/230915013-cc5a3bdf-b92d-48e1-b1c2-4c2aa9c85dc7.png">
      </td>
      <td>
<img width="200" alt="image" src="https://user-images.githubusercontent.com/61988699/230915187-0fe85c17-c450-43b3-820c-9f7795e96cdb.png">

<img width="200" alt="image" src="https://user-images.githubusercontent.com/61988699/230914531-2f59cf56-eeb4-4888-8a05-2c9cf567e874.png">
      </td>
    </tr>
</table>

## Proposed Changes
  - Move the sidebar to the top on smaller devices and make it full screen when not collapsed.

2023-04-10 15:34 UTC, StereoPT reviewed
If possible can you also reflect these changes in our Storybook?

2023-04-10 16:27 UTC, nunocaseiro requested changes

2023-04-10 16:27 UTC, nunocaseiro commented on frontend/src/components/Sidebar/Content/Content.tsx
> +  const setSidebarState = useSetRecoilState(sidebarState);
I agree, this can be a regular boolean state. It has few levels of prop drilling. @juniorboos, can give us your thoughts on using the recoil instead of a regular useState?

2023-04-10 16:43 UTC, juniorboos commented on frontend/src/components/Sidebar/Header/Header.tsx
> +            css={{ width: '58px', height: '58px', position: 'relative' }}
Changed!

2023-04-10 16:46 UTC, juniorboos commented on frontend/src/components/Sidebar/Content/Content.tsx
> +import { CollapsibleContent } from '../styles';
Changed!

2023-04-11 09:41 UTC, nunocaseiro approved these changes

2023-04-11 15:41 UTC, merged