feat: add Tiles responsiveness
xgeekshq/split pull request #1388
Opened 2023-04-13 12:32 UTC by juniorboos

Relates to:
- #971

## Screenshots (if visual changes)

## Proposed Changes
  - 
  -
  -

2023-04-13 13:27 UTC, StereoPT commented on frontend/src/components/Dashboard/Tiles/styles.tsx
> +  '> *': { flexGrow: 1 },
Can you explain the reason why use `flexGrow` instead of just ´flex: 1`?

Also, what are your opinions on having a fixed `minWidth`?

2023-04-13 14:04 UTC, juniorboos commented on frontend/src/components/Dashboard/Tiles/styles.tsx
> +  '> *': { flexGrow: 1 },
Yep, that can also work! I'm not sure why `minWidth` would be useful as I'm expecting `flex` to decide whether it should wrap or not based on the available space. I'm also enforcing that the text shouldn't break, so it will always have a readable width.

2023-04-13 14:05 UTC, juniorboos commented on frontend/src/components/Dashboard/Tiles/styles.tsx
> +const TileContainer = styled(Flex, {
Fair enough! I changed in 40d24ac.

2023-04-13 14:27 UTC, StereoPT commented on frontend/src/components/Dashboard/Tiles/styles.tsx
> +  '> *': { flexGrow: 1 },
I was thinking that so the Tiles would always have the same width.

2023-04-13 14:31 UTC, juniorboos commented on frontend/src/components/Dashboard/Tiles/styles.tsx
> +  '> *': { flexGrow: 1 },
Isn't that what `flex: 1` is doing? Not sure I understood.

2023-04-13 20:25 UTC, nunocaseiro approved these changes
LGMT 🚀

2023-04-13 20:26 UTC, nunocaseiro requested changes

2023-04-13 20:26 UTC, nunocaseiro commented on frontend/src/components/Dashboard/Tiles/Tile/styles.tsx
> +        height: '76px !important',
is it possible to use the stitches tokens instead of `px`?

2023-04-14 10:32 UTC, StereoPT commented on frontend/src/components/Dashboard/Tiles/styles.tsx
> +  '> *': { flexGrow: 1 },
The idea of the minWidth is to guarantee that each tile has exactly the same size.
As you can see, the `Your teams` is smaller than the `Active Members`

![image](https://user-images.githubusercontent.com/8330038/232021105-81c5020b-7d30-4d72-badc-84289f246b60.png)

It was just a design idea

2023-04-14 10:40 UTC, juniorboos commented on frontend/src/components/Dashboard/Tiles/styles.tsx
> +  '> *': { flexGrow: 1 },
Ooh, I see what you mean! I think it's hard to define a `minWidth` here as the `width` is defined by the text's length. So even if we define it as `300px` for example, there could be a Tile bigger than that because of the text inside it, and then they wouldn't be the same size once again. The only way to enforce the same size in this situations is using `maxWidth`, but I don't think that's scalable.

2023-04-14 10:47 UTC, StereoPT approved these changes
LGTM  🗝️

2023-04-14 13:04 UTC, tutods approved these changes

2023-04-14 13:10 UTC, nunocaseiro approved these changes

2023-04-14 13:10 UTC, merged