Feat reset pasword backend #108
xgeekshq/split pull request #197
Opened 2022-05-24 13:42 UTC by r-dmatos

Relates to  #106

Reset password,
user is given a token via email, 
there is an verification to find out if the token corresponds to the user,
user changes the password,
there is a verification to confirm the passwords given are the same.

Mention people who discussed this issue previously
@someone
-->

2022-05-25 14:49 UTC, dsousa12 commented
Please remove `public/icons`. Icons now is used with `<Icon />` component, where you need to pass `name` as prop.
The name it's the `id=""` in each `<symbol>` tag inside `Sprite.tsx`.

2022-05-25 14:49 UTC, dsousa12 commented
Please remove `.vscode/` folder inside `frontend`.

2022-05-25 14:59 UTC, dsousa12 commented
Please delete `package-lock.json` on root folder

2022-05-25 15:03 UTC, dsousa12 requested changes

2022-06-02 10:28 UTC, dsousa12 commented on frontend/.vscode/launch.json
> +{
Delete his file.
Don't make any sense

2022-06-02 10:28 UTC, dsousa12 commented on frontend/public/icons/envelope.svg
> +<svg width="55" height="52" viewBox="0 0 55 52" fill="none" xmlns="http://www.w3.org/2000/svg">
Delete the icon
If this icon does not exist on Sprite, please add it and use with `<Icon />` component

2022-06-02 10:28 UTC, dsousa12 commented on frontend/public/icons/eye.svg
> +<svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
Delete the icon
If this icon does not exist on Sprite, please add it and use with <Icon /> component

2022-06-02 10:28 UTC, dsousa12 commented on frontend/public/icons/gitHub.svg
> +<svg viewBox="0 0 60 60" fill="none" xmlns="http://www.w3.org/2000/svg">
Delete the icon
If this icon does not exist on Sprite, please add it and use with <Icon /> component

2022-06-02 10:28 UTC, dsousa12 commented on frontend/public/icons/info.svg
> +<svg viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
Delete the icon
If this icon does not exist on Sprite, please add it and use with <Icon /> component

2022-06-02 10:28 UTC, dsousa12 commented on frontend/public/icons/leftArrow.svg
> +<svg width="16" height="16" viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg">
Delete the icon
If this icon does not exist on Sprite, please add it and use with <Icon /> component

2022-06-02 10:28 UTC, dsousa12 commented on frontend/public/icons/microsoft.svg
> +<svg width="60" height="60" viewBox="0 0 60 60" fill="none" xmlns="http://www.w3.org/2000/svg">
Delete the icon
If this icon does not exist on Sprite, please add it and use with <Icon /> component

2022-06-02 10:28 UTC, dsousa12 commented on frontend/public/icons/toast/alert.svg
> +<svg width="31" height="32" viewBox="0 0 31 32" fill="none" xmlns="http://www.w3.org/2000/svg">
Delete the icon
If this icon does not exist on Sprite, please add it and use with <Icon /> component

2022-06-02 15:30 UTC, dsousa12 commented on backend/package.json
>  		"jwt-decode": "^3.1.2",
I don't have 100% sure, but I think you don't need a package to decode and encode.
Maybe you can use something like this: https://github.com/nestjs/jwt
But I will explore more about this topic

2022-06-03 08:18 UTC, dsousa12 requested changes

2022-06-03 08:18 UTC, dsousa12 commented on frontend/schema/schemaResetPasswordForm.tsx
> +			.regex(/.*[A-Z].*/, 'One uppercase character')
### Suggestion
Change this multiples regexs on this schema for:
```
z 
  .string()
  .nonempty('Please enter your password.')
  .regex(
        /^(?=.*[A-Za-z])(?=.*\d)(?=.*\W)[A-Za-z\d\W]{8,}$/,
        'Use at least 8 characters, upper and lower case letters, numbers and symbols like !”?$%^&).'
  ),
```
Basically that regex validate if have the leght of 8 chars, containing uppercase letter(s), lowecase letter(s), number(s) and special char(s).

2022-06-03 08:18 UTC, dsousa12 commented on frontend/components/auth/LoginForm/index.tsx
> -						{loading.credentials && <DotsLoading color="primary800" size={10} />}
Why you remove the `<DotsLoading>` component?

2022-06-03 08:47 UTC, r-dmatos commented on frontend/schema/schemaResetPasswordForm.tsx
> +			.regex(/.*[A-Z].*/, 'One uppercase character')
thank you for the suggestion. uploading changes now

2022-06-03 13:21 UTC, merged