[FIX]: Handling the minimum of users error
xgeekshq/split pull request #259
Opened 2022-06-24 15:51 UTC by joaosantos99

Fixes #254

## Screenshots (if visual changes)

![Screenshot 2022-06-24 at 16 49 46](https://user-images.githubusercontent.com/68588265/175571611-f0ae5a00-f607-4970-ba17-35781a8d262c.png)

## Proposed Changes

  - Added the error alert when when the team have less than 4 members
  - Stopped the creation of multiple boards ( cause of the issue error ) when the team have less than 4 members

This pull request closes #254

2022-06-24 18:50 UTC, nunocaseiro approved these changes

2022-06-27 08:05 UTC, dsousa12 requested changes

2022-06-27 08:05 UTC, dsousa12 commented on frontend/src/components/CreateBoard/SubTeamsTab/TeamSubTeamsConfigurations.tsx
> +	const minMembers = 4;
Not a problem, but as `minMembers` is a constant value maybe declare using uppercase letters (`MIN_MEMBERS`)

2022-06-27 08:05 UTC, dsousa12 commented on frontend/src/hooks/useCreateBoard.tsx
> +	const minMembers = 4;
Same:
> Not a problem, but as minMembers is a constant value maybe declare using uppercase letters (MIN_MEMBERS)

2022-06-27 08:13 UTC, joaosantos99 commented on frontend/src/components/CreateBoard/SubTeamsTab/TeamSubTeamsConfigurations.tsx
> +	const minMembers = 4;
It makes sense I will proceed to change

2022-06-27 08:21 UTC, dsousa12 approved these changes
LGTM 🚀

2022-06-27 08:35 UTC, merged