[BUG]: Team configuration is reset when clicking configurations and coming back to it
xgeekshq/split pull request #360
Opened 2022-07-22 16:22 UTC by joaosantos99

Fixes #350

## Proposed Changes

  - Created a state for identifying when the sub-boards don't need to be reset.

This pull request closes #350

2022-07-24 16:12 UTC, dsousa12 requested changes

2022-07-24 16:12 UTC, dsousa12 commented on frontend/src/components/CreateBoard/SubTeamsTab/MainBoardCard.tsx
> +	const [newBoard, setNewBoard] = useRecoilState(newBoardState);
Why you need a new **Recoil** state to storage a boolean?

2022-07-25 08:33 UTC, joaosantos99 commented on frontend/src/components/CreateBoard/SubTeamsTab/MainBoardCard.tsx
> +	const [newBoard, setNewBoard] = useRecoilState(newBoardState);
Because when the user changes from the teams configuration to the board configuration and switch back again to the teams configuration, it re-renders the component and in the useEffect resets any change on the teams. So i added a booleon to know when to reset the teams cahnges.

2022-07-25 15:38 UTC, dsousa12 commented on frontend/src/components/CreateBoard/SubTeamsTab/MainBoardCard.tsx
> +	const [newBoard, setNewBoard] = useRecoilState(newBoardState);
Ok, but you can't avoid the re-renders without another state?

2022-07-25 15:38 UTC, dsousa12 commented on frontend/src/components/CreateBoard/SubTeamsTab/MainBoardCard.tsx
> +	const [newBoard, setNewBoard] = useRecoilState(newBoardState);
If not, maybe create a normal `useState` and send by props the `set` function.
Because you don't use this recoil state in other places I think.

But wait for other reviews.

2022-07-26 09:27 UTC, joaosantos99 commented on frontend/src/components/CreateBoard/SubTeamsTab/MainBoardCard.tsx
> +	const [newBoard, setNewBoard] = useRecoilState(newBoardState);
I initially i used `useState`, but later i needed a way to reset the state when someone clicked on the "Add new board" button so i switched to the atom.
Do you have any suggestion to solve that problem?

2022-07-28 09:23 UTC, dsousa12 submitted a review, later dismissed
LGTM 🚀

2022-07-28 10:28 UTC, dsousa12 approved these changes

2022-07-28 10:36 UTC, merged