Feat swagger documentation
xgeekshq/split pull request #371
Opened 2022-07-25 15:28 UTC by dsousa12

Relates to #296 

## Screenshots

![image](https://user-images.githubusercontent.com/104842894/180815714-3c80dc1e-c52c-4097-afe8-97105f9d06f0.png)
![image](https://user-images.githubusercontent.com/104842894/180816093-a024757a-b72a-4685-a9b5-2ed8e3669df4.png)

## Proposed Changes

  - Install **Swagger** packages;
  - Use decorators for type responses, parameteres and body on each endpoint;
  - Create default errors response class's to use on **Swaggger**.

This pull request closes #296

2022-08-01 17:36 UTC, nunocaseiro requested changes
Amazing job! Before the merge please verify if this pr doesn't break any feature

2022-08-01 17:36 UTC, nunocaseiro commented on backend/src/app.module.ts
> +	AzureModule,
```suggestion
```

This module should be imported optionally

2022-08-01 17:36 UTC, nunocaseiro commented on backend/src/modules/cards/controller/cards.controller.ts
> +	@ApiParam({ name: 'targetCardId', type: String })
```suggestion
	@ApiParam({ name: 'itemId', type: String })
```

2022-08-02 11:51 UTC, geomarb requested changes
Congratulations there is a huge and great work here, and the most import part: it works perfectly! There are just some few changes to be done that where done.

2022-08-02 11:51 UTC, geomarb commented on frontend/src/api/boardService.tsx
> +		`/boards/${updateCardPosition.boardId}/card/${updateCardPosition.cardId}/update-card-position`,
Please change the method for **`PATCH`**  and the endpoint for `/boards/${updateCardPosition.boardId}/card/${updateCardPosition.cardId}/position`.

`PUT` should be used when you need replace the entire resource. The `PATCH` method says you are asking for an update action, in this way you don't need explicit mention `update` in the endpoint, and since you already are under `card` endpoint you can disregard it as well.

Don't forget to reflect these changes in the backend as well.

2022-08-02 16:42 UTC, geomarb commented on backend/src/libs/exceptions/messages.ts
> +};
This approach is ok, but when we have it like that we need change in two places to add or remove a new const. Not a big deal, but as less changes to get the job done is better. It is just a comment, no changes are needed here.

2022-08-02 16:45 UTC, geomarb approved these changes
Perfect!!!

2022-08-03 13:09 UTC, nunocaseiro approved these changes
Great job!

2022-08-03 14:22 UTC, merged