[FEATURE]: config responsible on the boardSettings
xgeekshq/split pull request #374
Opened 2022-07-26 15:29 UTC by CatiaBarroco-xgeeks

Relates to #369 

## Screenshots (if visual changes)

![imagem](https://user-images.githubusercontent.com/104831678/181046225-14b15acc-6e67-47d1-9ce0-aaa067b2540e.png)

![imagem](https://user-images.githubusercontent.com/104831678/181047069-2c080216-8726-4378-8600-bc95d13ad5bc.png)

## Proposed Changes

  - added the possibility to change the responsibility of the board after it has been created
  - CSS changed according to final version

Mention people who discussed this issue previously
@dsousa12 @f-morgado 

This pull request closes #369

2022-07-27 07:55 UTC, dsousa12 requested changes

2022-07-27 07:55 UTC, dsousa12 commented on frontend/src/components/Board/Settings/index.tsx
> +														}}
You try use without import the color and use it like stitches way?

Something like:
```suggestion
														colors={{
															bg: '$highlight2Lighter',
															fontColor: '$highlight2Dark'
'														}}
```

2022-07-27 07:55 UTC, dsousa12 commented on frontend/src/components/Board/Settings/index.tsx
> +import { highlight2Colors } from 'styles/stitches/partials/colors/highlight2.colors';
If the comment I leave bellow works, please remove this import.

2022-07-27 07:55 UTC, dsousa12 commented on frontend/src/components/Board/Settings/index.tsx
> +														}}
Already tested it and works without import `highlight2Colors`.

2022-07-27 14:43 UTC, geomarb commented on backend/src/modules/boards/services/update.board.service.ts
> +		return users.find((user) => user.role === BoardRoles.RESPONSIBLE);
There is a way to get the result in the first `find` without the need of the second find, you can find an example [here](https://www.mongodb.com/docs/manual/reference/method/db.collection.find/ ).
PS: This is a small and insignificant issue that can be disregarded, but could be done more for learning purposes.

2022-07-28 06:32 UTC, dsousa12 commented on backend/src/modules/boards/services/update.board.service.ts
> +		return users.find((user) => user.role === BoardRoles.RESPONSIBLE);
Thanks @geomarb, I don't remember that.
Already done, thanks again 😉

2022-07-28 09:55 UTC, geomarb commented on backend/src/modules/boards/services/update.board.service.ts
> +			if (boardData.users && isSubBoard) {
It would be nice to have some comments in this part explaining what it does.

2022-07-28 10:30 UTC, dsousa12 commented on backend/src/modules/boards/services/update.board.service.ts
> +			if (boardData.users && isSubBoard) {
Agree, but basically to you understand:
1. First validate if the user have permissions to edit this specific board
2. If have permissions, validate if have an array of users (only have when change responsible) and is a sub-board.
    - **Note:** only on sub-boards have the **responsible** role, so needs to check if is a sub-board.

2022-07-28 10:41 UTC, geomarb commented on frontend/src/components/Board/Settings/index.tsx
> +		mutate({
Please, remove this console.log.

2022-07-28 15:59 UTC, geomarb requested changes
There are some small issues to be reviewed such as a the rule to avoid changing maxVotes and the getResponsible function.

2022-08-01 08:13 UTC, geomarb commented on backend/src/modules/boards/services/update.board.service.ts
> +	private async checkIfUserIsResponsible(userId: string, boardId: string): Promise<boolean> {
It is ok like it is. A shorter version could be `isUserResponsiple(...)`.

2022-08-01 16:41 UTC, geomarb requested changes
LGTM, but it has some small adjusts that could be done, I put a comment the in the lines where I believe could be different. 
We need check with the designer about the way we change the stakeholder as a user, since we need click three times and the lottery button doesn't looks like a button what is not so intuitive.
Talking about the design/user experience it would be better if we could keep Save button deactivated until we have any changes.

2022-08-01 16:41 UTC, geomarb commented on backend/src/modules/boards/services/update.board.service.ts
> +							replaceAll(String(currentResponsibleId), ['"', '(', ')', 'ObjectId'], ''),
It seems we can get the currentResponsibleId without the help of replaceAll (which could be dropped if it is not used somewhere else).

2022-08-01 16:41 UTC, geomarb commented on backend/src/libs/utils/replace-all.ts
> +const replaceAll = (value: string, find: string[], replace: string): string => {
If change the way to get the userId directly instead of an object, we could remove this function.

2022-08-02 06:27 UTC, dsousa12 commented on backend/src/modules/boards/services/update.board.service.ts
> +							replaceAll(String(currentResponsibleId), ['"', '(', ')', 'ObjectId'], ''),
I create this function because the other two IDs return only the id, but the `currentResponsibleId` returns with `ObjectId('user-id')`.
So to prevent any error, I made this function to replace the `ObjectId`, `()` and `"`

2022-08-02 12:39 UTC, geomarb commented on backend/src/modules/boards/services/update.board.service.ts
> +							replaceAll(String(currentResponsibleId), ['"', '(', ')', 'ObjectId'], ''),
Got it now thanks! As it has a very specific purpose it would be better to rename `replaceAll()` to something like 
`getIdFromObjectId(objectId: ObjectId) {...}` and inside of this function do all the job needed as converting ObjectId to string and the array need to clean data inside the function.

2022-08-03 10:46 UTC, geomarb commented on backend/src/libs/utils/replace-all.ts
> +const replaceAll = (value: string, find: string[], replace: string): string => {
I am setting this request as resolved as it works, in this way we don't need to hold this PR. This change is optional.

2022-08-03 10:48 UTC, geomarb commented on backend/src/modules/boards/services/update.board.service.ts
> +							replaceAll(String(currentResponsibleId), ['"', '(', ')', 'ObjectId'], ''),
I set it as resolved as this change is optional.

2022-08-04 13:27 UTC, dsousa12 commented
## Note:

To avoid errors related with event listener created to use when user press key, close the dialog and submit the form, we need create a `span`. around the dialog.
This `span`. contains a `ref={}` and the event listener is used only on the content of this `span`.

2022-08-05 06:13 UTC, dsousa12 approved these changes

2022-08-05 06:13 UTC, merged