[FEATURE]: User vote count limit on a specific board verification
xgeekshq/split pull request #414
Opened 2022-08-18 13:16 UTC by CatiaBarroco-xgeeks

Relates to #409

## Proposed Changes

  - backend protection when user adds votes

Mention people who discussed this issue previously
@f-morgado 

This pull request closes #409

2022-08-18 16:51 UTC, nunocaseiro requested changes

2022-08-18 16:51 UTC, nunocaseiro commented on backend/src/modules/votes/services/create.vote.service.ts
> +		const myUser = await this.boardUserModel.find({ board: boardId, user: userId });
Try to avoid personal names when naming variables

```suggestion
		const userFound = await this.boardUserModel.find({ board: boardId, user: userId });
```
or

```suggestion
		const boardUser = await this.boardUserModel.find({ board: boardId, user: userId });
```

2022-08-18 16:51 UTC, nunocaseiro commented on backend/src/modules/votes/services/create.vote.service.ts
> +		const voteAllowed = myUser[0].votesCount + 1 <= maxVotes;
Does the find method return more than one value? Why are you accessing the position 0?

2022-08-19 08:48 UTC, CatiaBarroco-xgeeks commented on backend/src/modules/votes/services/create.vote.service.ts
> +		const myUser = await this.boardUserModel.find({ board: boardId, user: userId });
thanks

2022-08-19 08:52 UTC, nunocaseiro approved these changes
LGTM 🚀

2022-08-21 19:20 UTC, dsousa12 approved these changes

2022-08-21 19:20 UTC, dsousa12 commented on backend/src/modules/votes/services/create.vote.service.ts
> +		const maxVotes = board?.maxVotes as Number;
Why not use `Number(board?.maxVotes)` if you want to force the type as a number

2022-08-21 19:20 UTC, dsousa12 commented on backend/src/modules/votes/services/create.vote.service.ts
> +	private async voteEnable(boardId: string, userId: string): Promise<boolean> {
```suggestion
	private async canUserVote(boardId: string, userId: string): Promise<boolean> {
```

2022-08-21 19:20 UTC, dsousa12 commented on backend/src/modules/votes/services/create.vote.service.ts
> +		return userCanVote;
```suggestion
		return maxVotes === null || voteAllowed;
```

2022-08-21 19:20 UTC, dsousa12 commented on backend/src/modules/votes/services/create.vote.service.ts
> +	async incrementVoteUser(boardId: string, userId: string) {
Is this method only used internally?
If yes please change it to `private`.

2022-08-21 19:20 UTC, dsousa12 commented on backend/src/modules/votes/services/create.vote.service.ts
> +		return null;
Instead return `null`, why not return an exception?

```ts
throw new BadRequestException('Error adding a vote')
```

**Note:** maybe you can use generic messages or something else.

2022-08-21 19:20 UTC, dsousa12 commented on backend/src/modules/votes/services/create.vote.service.ts
> +		return null;
Same here!

2022-08-21 19:20 UTC, dsousa12 commented on frontend/src/components/Board/Card/CardFooter.tsx
> +/* eslint-disable @typescript-eslint/no-unused-vars */
Why you disable this rule for the entire file?

2022-08-23 07:51 UTC, dsousa12 approved these changes

2022-08-23 07:51 UTC, dsousa12 commented on backend/src/modules/votes/services/create.vote.service.ts
> +		if (!boardUser) throw Error(UPDATE_FAILED);
```suggestion
		if (!boardUser) throw BadRequestException(UPDATE_FAILED);
```

2022-08-25 17:20 UTC, mourabraz approved these changes
LGTM 🚀

2022-08-25 17:20 UTC, merged