[BUG] Accessing a deleted board
xgeekshq/split pull request #479
Opened 2022-10-12 09:34 UTC by CatiaBarroco-xgeeks

Relates to #464

## Screenshots (if visual changes)

## Proposed Changes

  - if someone deletes a certain board the other users will have an update of the list of boards
  - or if the other users are inside the board they will be redirected to a page warning with the information that the board has been deleted

Mention people who discussed this issue previously
@f-morgado @joaosantos99 

This pull request closes #464

2022-10-13 14:37 UTC, nunocaseiro requested changes

2022-10-13 14:37 UTC, nunocaseiro commented on backend/src/modules/socket/gateway/socket.gateway.ts
> +		this.server.except(excludedClient).emit('updateBoardList');
```suggestion
		this.server.to(roomId).except(excludedClient).emit('updateBoardList');
```

I think you should not notify all server. The `roomId` should be the same as the one sent when the user joined the room  (line 51 - payload.boards)

2022-10-13 14:37 UTC, nunocaseiro commented on backend/src/modules/socket/interfaces/joinPayloadBoards.interface.ts
> +	boards: string;
I think the `boards` prop should be renamed to something that better identifies that variable's purpose. I think it should  have something related to the board's list socket room id. Like `roomId` or `teamId`

2022-10-13 14:37 UTC, nunocaseiro commented on frontend/src/components/Boards/MyBoards/index.tsx
> +	});
This can be very exhaustive achieving a giant string ID. Here we can find which teams/team the user is belonging to and he is seeing on the dashboard then send the team id(s) as the room id(s) to join. When we will have personal boards this strategy will be a little different. For now, you can choose the xgeeks team id as a room id for the socket server

2022-10-13 14:37 UTC, nunocaseiro commented on frontend/src/hooks/useSocketBoardIO.ts
> +export const useSocketBoardIO = (boards: string | undefined): string | undefined => {
```suggestion
export const useSocketBoardIO = (teamId: string | undefined): string | undefined => {
```

2022-10-13 14:37 UTC, nunocaseiro commented on frontend/src/hooks/useSocketBoardIO.ts
> +			newSocket.emit('join', { boards: 'listBoards' });
```suggestion
			newSocket.emit('joinBoards', { roomId: teamId });
```
This `ROOM_ID` is the one that you will receive on the query param of the delete method

2022-10-13 14:37 UTC, nunocaseiro commented on frontend/src/hooks/useSocketBoardIO.ts
> +			queryClient.invalidateQueries('boards');
```suggestion
		newSocket.on(teamId, () => {
			queryClient.invalidateQueries('boards');
```

2022-10-13 14:37 UTC, nunocaseiro commented on frontend/src/hooks/useSocketBoardIO.ts
> +	}, [boards, queryClient, setSocket]);
```suggestion
	}, [teamId, queryClient, setSocket]);
```

2022-10-13 14:37 UTC, nunocaseiro commented on backend/src/modules/socket/gateway/socket.gateway.ts
> +	sendUpdatedBoards(excludedClient: string) {
```suggestion
	sendUpdatedBoards(excludedClient: string, roomId: string) {
```

2022-10-13 14:37 UTC, nunocaseiro commented on backend/src/modules/socket/gateway/socket.gateway.ts
> +		client.join(payload.boards);
```suggestion
		client.join(payload.roomId);
```

2022-10-14 09:17 UTC, CatiaBarroco-xgeeks commented on backend/src/libs/dto/param/base.param.ts
> +}
yes, you are right. this was a test and we forgot to delete

2022-10-14 09:35 UTC, CatiaBarroco-xgeeks commented on backend/src/modules/boards/controller/boards.controller.ts
> +		@Query() { socketId }: { socketId?: string },
Resolve

2022-10-21 10:32 UTC, f-morgado commented on backend/src/modules/socket/gateway/socket.gateway.ts
> +		client.join(payload.boards);
Took care of all changes you requested 🦾

2022-10-21 16:26 UTC, closed without merging