[FEATURE]: change role of team member
xgeekshq/split pull request #566
Opened 2022-11-09 14:55 UTC by CatiaAntunes96

Relates to #548 

## Screenshots (if visual changes)
![image](https://user-images.githubusercontent.com/59372326/200863160-c18bfbf3-1700-4eed-be43-0f2b220e7524.png)

## Proposed Changes

  - Add popover that looks like a select to change role of the member

This pull request closes #548

2022-11-09 21:15 UTC, nunocaseiro requested changes

2022-11-09 21:15 UTC, nunocaseiro commented on frontend/src/components/Teams/CreateTeam/CardMember/RoleSettings.tsx
> +						css={{ px: '$16' }}
The `popoverItem` background should have the `primary50` color and the popover content doesn't have padding 😃 

![Captura de ecrã 2022-11-09, às 20 43 19](https://user-images.githubusercontent.com/90208434/200941943-c93c9c4d-52e4-445e-b852-4aec83686d10.png)

2022-11-10 10:27 UTC, mourabraz approved these changes
ACK 🚀

2022-11-10 10:48 UTC, nunocaseiro approved these changes
LGTM 🚀 great job

2022-11-10 10:58 UTC, merged