Feat/add get team endpoint
xgeekshq/split pull request #592
Opened 2022-11-17 17:44 UTC by CatiaAntunes96

Relates to #587 

## Proposed Changes

  - Fix returned value from getTeam endpoint
  - Change color of blob personal to violet
  - Remove link to boards list page from team card (needs to be added later)
  - Add getTeam query hook and endpoint to frontend
  - -fix layout of team card

2022-11-17 18:28 UTC, nunocaseiro requested changes

2022-11-17 18:28 UTC, nunocaseiro commented on frontend/src/components/Teams/MyTeams/partials/CardTeam/BoardsInfo.tsx
> +							{' '}
```suggestion
```
You can remove this white space if it isn't needed

2022-11-17 18:28 UTC, nunocaseiro commented on frontend/src/components/Primitives/Tooltip/styles.tsx
> +	minWidth: '141px',
```suggestion
	minWidth: '$141',
```

2022-11-17 18:28 UTC, nunocaseiro commented on frontend/src/hooks/useTeamUtils.tsx
> +const useTeamUtils = () => {
The return type of this hook is missing

2022-11-17 18:28 UTC, nunocaseiro commented on frontend/src/hooks/useTeam.tsx
> +	const fetchTeam = useQuery(['team', teamId], () => getTeamRequest(teamId as string), {
```suggestion
	const fetchTeam = useQuery(['team', teamId], () => getTeamRequest(teamId), {
```

You can avoid forcing the `teamId` as a string after setting the return type for `useTeamUtils`

2022-11-18 10:43 UTC, CatiaAntunes96 commented on frontend/src/hooks/useTeam.tsx
> +	const fetchTeam = useQuery(['team', teamId], () => getTeamRequest(teamId as string), {
As the return type of router.query is: `string | string[] | undefined`, I have to keep the teamId as string, so that the function accepts the argument. Do you have another solution to avoid using the `as string` ? @nunocaseiro

2022-11-18 11:51 UTC, nunocaseiro approved these changes
LGTM 🚀

2022-11-18 11:54 UTC, merged