feat: add delete team endpoint
xgeekshq/split pull request #633
Opened 2022-11-25 12:04 UTC by patricia-mdias

Relates to #495 

## Proposed Changes

  - add new endpoint to delete teams

@CatiaAntunes96 

This pull request closes #495

2022-11-25 15:40 UTC, nunocaseiro requested changes

2022-11-25 15:40 UTC, nunocaseiro commented on backend/src/modules/teams/services/delete.team.service.ts
> +	}
Good job here with the transactions. I think you followed the delete board method however, as mongo doesn't have the cascade strategy you should also implement it by deleting manually the teamUsers using the `deleteMany` like we did to the `deleteBoardUsers`. You can check the `delete.board.service` file and do something similar for the teams

2022-11-26 18:34 UTC, rpvsilva requested changes

2022-11-26 18:34 UTC, rpvsilva commented on backend/src/modules/teams/controller/team.controller.ts
> +		return result;
The controller shouldn't have any kind of logic, you can do this on service side

2022-11-28 10:28 UTC, patricia-mdias commented on backend/src/modules/teams/controller/team.controller.ts
> +		return result;
The service function delete() returns a boolean, indicating whether the delete query was successful or not, I believe I need this kind of information to return a Bad Request Status in the Controller. What do you think?

2022-11-28 10:48 UTC, nunocaseiro commented on backend/src/modules/teams/controller/team.controller.ts
> +		return result;
You can change the way we are handling the errors by throwing the exception on the service and just calling the service method in the controller

2022-11-28 16:49 UTC, nunocaseiro requested changes

2022-11-28 17:11 UTC, nunocaseiro submitted a review, later dismissed
LGTM 🚀 great job!

2022-11-28 17:30 UTC, rpvsilva requested changes

2022-11-28 18:02 UTC, rpvsilva approved these changes
LGTM 🔥

2022-11-28 18:05 UTC, merged