feat: add stakeholder permissions team
xgeekshq/split pull request #650
Opened 2022-11-30 12:10 UTC by patricia-mdias

Relates to #638 

## Screenshots (if visual changes)
![BB9B4E18-DD6D-44D0-84B0-C0DA88C715E3](https://user-images.githubusercontent.com/116013814/204792356-0f2af54e-4d5f-46c4-a79a-a21bc01e49af.png)
![E3D090F9-9F19-4A97-A509-C2683FB276B5](https://user-images.githubusercontent.com/116013814/204792503-9fde9994-6a15-4b65-a32f-61d67614cca8.png)

## Proposed Changes

  - Allow stakeholders edit and remove teams

This pull request closes #638

2022-11-30 16:49 UTC, nunocaseiro submitted a review, later dismissed
LGTM 🔥

2022-11-30 16:49 UTC, nunocaseiro commented on frontend/src/components/Teams/TeamsList/partials/CardTeam/CardBody.tsx
> +    );
```suggestion
    return  team && [TeamUserRoles.ADMIN, TeamUserRoles.STAKEHOLDER].includes(myUser?.role)
```

This is just a suggestion. It's another way to do the same in a more elegant way

2022-11-30 20:53 UTC, rpvsilva requested changes

2022-11-30 20:53 UTC, rpvsilva commented on backend/src/libs/guards/teamRoles.guard.ts
> +			const isTeamAdminOrStakeholder = permissions.includes(userFound?.role);
The naming is not the best because the permissions can change within the project, you can call it, for example, `hasPermissions`

2022-12-02 14:48 UTC, nunocaseiro requested changes

2022-12-02 14:48 UTC, nunocaseiro commented on frontend/src/components/Teams/TeamsList/partials/CardTeam/CardBody.tsx
> +    return team && [TeamUserRoles.ADMIN, TeamUserRoles.STAKEHOLDER].includes(myUser!.role);
```suggestion
    if (!myUser) {
      return false
    }
    
     return team && [TeamUserRoles.ADMIN, TeamUserRoles.STAKEHOLDER].includes(myUser.role);
```

Be careful on force unwrapping the `myUser`. You can check if the user isn't found and then return false

2022-12-02 14:48 UTC, nunocaseiro commented on backend/src/libs/guards/teamRoles.guard.ts
> +			return hasPermissions;
```suggestion
			return permissions.includes(userFound?.role) || user.isSAdmin
```

2022-12-02 15:10 UTC, patricia-mdias commented on backend/src/libs/guards/teamRoles.guard.ts
> +			return hasPermissions;
I made this change on my other branch that is waiting on PR.

2022-12-02 15:51 UTC, nunocaseiro submitted a review, later dismissed
LGTM 🔥

2022-12-02 17:54 UTC, rpvsilva approved these changes

2022-12-05 15:46 UTC, nunocaseiro approved these changes

2022-12-05 15:53 UTC, merged