fix: delete team removes associated boards
xgeekshq/split pull request #653
Opened 2022-12-02 14:07 UTC by patricia-mdias

Fixes #651 

## Proposed Changes

  - Delete boards of deleted team.

This pull request closes #651

2022-12-02 15:01 UTC, rpvsilva requested changes

2022-12-02 15:01 UTC, rpvsilva commented on backend/src/modules/boards/services/delete.board.service.ts
> +			if (!deleteSuccessful) throw new BadRequestException(DELETE_FAILED);
This if condition won't be triggered, because the `deleteSuccessful` value is equal to Promise<...> you need to await each request, for this you can use the `forawait`

2022-12-02 15:01 UTC, rpvsilva commented on backend/src/modules/teams/services/delete.team.service.ts
> +
Forgot to remove?

2022-12-02 15:27 UTC, patricia-mdias commented on backend/src/modules/boards/services/delete.board.service.ts
> +			if (!deleteSuccessful) throw new BadRequestException(DELETE_FAILED);
Adding await before the "this.deleteBoardBoardUsersAndSchedules(board._id.toString(), false);"?

2022-12-02 17:52 UTC, rpvsilva reviewed
What do you think about this?

2022-12-02 17:52 UTC, rpvsilva commented on backend/src/modules/boards/services/delete.board.service.ts
> +		);
```suggestion
		const promises = teamBoards.map((board) =>
			this.deleteBoardBoardUsersAndSchedules(board._id.toString(), false)
		);
		
		await Promise.all(promises).catch((errors) => do something)
```

2022-12-05 16:11 UTC, rpvsilva approved these changes

2022-12-05 17:05 UTC, merged