feat: user card actions
xgeekshq/split pull request #658
Opened 2022-12-06 13:23 UTC by RafaelSBatista97

#599 

Relates to #594 

## Screenshots (if visual changes)
As Super Admin:
![image](https://user-images.githubusercontent.com/118206043/205910792-132400c4-6a36-4da0-a667-e68f6bc00a68.png)

As member:
![image](https://user-images.githubusercontent.com/118206043/205911124-810dfdd1-7c33-47f2-81f0-64d0262ccc89.png)

## Proposed Changes
  - As a super admin the switch button should be visible and editable. This action makes a request to the backend in order to change the user role in the app. 
  - The edit button and when the user clicks in the user's name should redirect to the user details. 
  - The delete button should be present and this will be done in issue https://github.com/xgeekshq/split/issues/600. 
  - Both icons and user's name must have a hover behaviour.
  - A member only sees the user teams count and which user is an admin.

Mention people who discussed this issue previously
@GuiSanto 

This pull request closes #599

2022-12-07 11:40 UTC, rpvsilva requested changes

2022-12-07 11:40 UTC, rpvsilva commented on backend/src/libs/guards/superAdmin.guard.ts
> +	}
Can you confirm to me one thing? If you return `false`, without this `try { ... } catch () { ... }` and check what error it returns? If it returns a `ForbiddenException` you can remove this try catch and only return the `request.user.isSAdmin`

2022-12-07 11:40 UTC, rpvsilva commented on backend/src/modules/users/controller/users.controller.ts
> +	}
```suggestion
	updateUserSuperAdmin(@Body() userData: UpdateUserDto) {
		return this.updateUserApp.updateSuperAdmin(userData);
	}
```

2022-12-07 13:18 UTC, RafaelSBatista97 commented on backend/src/libs/guards/superAdmin.guard.ts
> +	}
yes, works fine without the try catch.

2022-12-07 16:44 UTC, rpvsilva approved these changes
LGTM 🔥

2022-12-07 17:23 UTC, rpvsilva requested changes

2022-12-07 17:23 UTC, rpvsilva commented on frontend/src/components/Users/UsersList/partials/CardUser/CardBody.tsx
> +  }
```suggestion
  const teamsSeparatedByComma = teamsNames?.join(', ') || '';
```

2022-12-07 17:43 UTC, GuiSanto commented on frontend/src/components/Users/UsersList/partials/CardUser/CardBody.tsx
> +  }
nice

2022-12-09 11:59 UTC, rpvsilva requested changes

2022-12-09 14:37 UTC, rpvsilva submitted a review, later dismissed

2022-12-12 10:08 UTC, nunocaseiro commented on frontend/src/components/Users/UsersList/partials/CardUser/SuperAdmin.tsx
> +    }
Is this working when something goes wrong? you have access to the request status

2022-12-12 14:39 UTC, RafaelSBatista97 commented on frontend/src/components/Users/UsersList/partials/CardUser/SuperAdmin.tsx
> +    }
yes, it's working when something goes wrong. At least we tested it by putting a wrong url on the fetch and it goes to the catch showing the error.

2022-12-12 18:22 UTC, rpvsilva approved these changes

2022-12-13 10:49 UTC, nunocaseiro requested changes

2022-12-13 10:49 UTC, nunocaseiro commented on frontend/src/components/Users/UsersList/partials/CardUser/SuperAdmin.tsx
> +      </Flex>
```suggestion
      <Flex css={{ ml: '$2', display: 'flex', alignItems: 'center' }}>
          <ConfigurationSettings
            handleCheckedChange={handleSuperAdminChange}
            isChecked={checkedState}
            text=""
            title="Super Admin"
            disabled={loggedUserId !== userId ? undefined : isDisabledState}
            styleVariant={loggedUserId !== userId ? undefined : isDisabledState}
          />
      </Flex>
```

2022-12-14 09:58 UTC, nunocaseiro approved these changes
LGTM 🚀

2022-12-14 09:59 UTC, merged