feat: team repository
xgeekshq/split pull request #661
Opened 2022-12-06 17:06 UTC by nunocaseiro

## Proposed Changes

  - Add team and team-user repository

2022-12-07 11:34 UTC, rpvsilva requested changes

2022-12-07 11:34 UTC, rpvsilva commented on backend/src/libs/repositories/mongo/mongo-generic.repository.ts
> +	findOneById(id: any, selectedValues?: SelectedValues<T>, populate?: any): Promise<T> {
You should type the `populate` property

2022-12-07 11:34 UTC, rpvsilva commented on backend/src/modules/teams/services/create.team.service.ts
>  	async createTeamUsers(teamUsers: TeamUserDto[], teamId: string) {
```suggestion
	createTeamUsers(teamUsers: TeamUserDto[], teamId: string) {
```

2022-12-07 11:39 UTC, nunocaseiro commented on backend/src/libs/repositories/interfaces/base.repository.interface.ts
> +	endSession();
These types just return void, do you think they should have the void type?

2022-12-07 14:33 UTC, rpvsilva commented on backend/src/libs/repositories/interfaces/base.repository.interface.ts
> +	endSession();
Yes please, since it's an interface it's important to be fully typed

2022-12-12 10:06 UTC, rpvsilva approved these changes
LGTM 🔥

2022-12-12 10:14 UTC, merged