Feat/automatically update isnewjoiner status
xgeekshq/split pull request #662
Opened 2022-12-06 17:17 UTC by CatiaAntunes96

Relates to #636 

## Proposed Changes

  - Change the logic of creating the teams of the subboards.
  - If there aren't enough members who can be responsible for a subboard, the oldest new joiner user will be chosen
  - Everytime a board is created, a verification function is executed, to check if the new joiners are still new joiners, updating accordingly.

This pull request closes #636

2022-12-07 14:46 UTC, rpvsilva requested changes

2022-12-07 14:46 UTC, rpvsilva commented on backend/src/modules/auth/shared/login.auth.ts
> +		userAzureCreatedAt,
Since this is a shared logic within the authentication, is it a good idea to call this property `userAzureCreatedAt`, imagine that I login using GitHub? What do you think we could do here? @nunocaseiro

2022-12-07 14:46 UTC, rpvsilva commented on backend/src/modules/azure/services/auth.azure.service.ts
> +		return `https://graph.microsoft.com/v1.0/users?$search="mail:${email}" OR "displayName:${email}" OR "userPrincipalName:${email}"&$orderbydisplayName&$select=displayName,mail,userPrincipalName,creat
Could you extract this url to a separate function outside the class? You can use it like:
```javascript
const Endpoints = {
  getAzureUserInfo: (email: string) => `...`
}
```
And then use it like `Endpoints.getAzureUserInfo(email)`. What do you think?

2022-12-07 14:46 UTC, rpvsilva commented on backend/src/modules/azure/services/auth.azure.service.ts
> +	async getUserFromAzure(email: string) {
Related to above, then you just need this method. Also we need to remove this "normal" axios and use the axios module from nestjs, but that's different topic

2022-12-07 14:46 UTC, rpvsilva commented on backend/src/modules/boards/services/create.board.service.ts
> +		return currentDate.isBefore(maxDateToBeNewJoiner) || currentDate.isSame(maxDateToBeNewJoiner);
As a personal preference I suggest using `date-fns` because it uses the native `Date` class from JS instead of creating an instance like `moment`, can you check it?

2022-12-07 15:19 UTC, nunocaseiro commented on backend/src/modules/auth/shared/login.auth.ts
> +		userAzureCreatedAt,
Yeah I think we should change the var name to something more generic

2022-12-07 15:58 UTC, CatiaAntunes96 commented on backend/src/modules/auth/shared/login.auth.ts
> +		userAzureCreatedAt,
What do you think about  **providerAccountCreatedAt** for the name of the variable? @nunocaseiro @rpvsilva

2022-12-07 16:08 UTC, CatiaAntunes96 commented on backend/src/modules/azure/services/auth.azure.service.ts
> +		return `https://graph.microsoft.com/v1.0/users?$search="mail:${email}" OR "displayName:${email}" OR "userPrincipalName:${email}"&$orderbydisplayName&$select=displayName,mail,userPrincipalName,creat
It seems a good idea. What do you think about creating a new file , called endpoints, in the libs/utils folder, and then use it like you suggested? @rpvsilva

2022-12-07 16:25 UTC, CatiaAntunes96 commented on backend/src/modules/boards/services/create.board.service.ts
> +		return currentDate.isBefore(maxDateToBeNewJoiner) || currentDate.isSame(maxDateToBeNewJoiner);
You are right, like moment, dayjs also returns an instance. I will use `date-fns`

2022-12-07 16:46 UTC, rpvsilva commented on backend/src/modules/azure/services/auth.azure.service.ts
> +		return `https://graph.microsoft.com/v1.0/users?$search="mail:${email}" OR "displayName:${email}" OR "userPrincipalName:${email}"&$orderbydisplayName&$select=displayName,mail,userPrincipalName,creat
I don't think that this is necessary, keep this things in the domain

2022-12-07 16:47 UTC, rpvsilva commented on backend/src/modules/auth/shared/login.auth.ts
> +		userAzureCreatedAt,
Seems good to me 😉

2022-12-09 10:17 UTC, rpvsilva requested changes

2022-12-09 10:17 UTC, rpvsilva commented on frontend/package.json
> +		"dayjs": "^1.11.7",
Could you install de `date-fns` on frontend too? To keep a standard on both sides

2022-12-09 15:05 UTC, rpvsilva requested changes

2022-12-09 19:44 UTC, rpvsilva approved these changes
For me backend is good 🔥 wait until nuno's approval for frontend

2022-12-12 10:13 UTC, nunocaseiro submitted a review, later dismissed
Amazing job 🔥

2022-12-12 18:21 UTC, rpvsilva approved these changes

2022-12-13 09:34 UTC, merged