feat: select retro type
xgeekshq/split pull request #681
Opened 2022-12-14 16:38 UTC by CatiaAntunes96

Relates to #675

## Screenshots (if visual changes)
![image](https://user-images.githubusercontent.com/59372326/207653721-feb44486-0522-496a-85d5-35213b5bf436.png)
![image](https://user-images.githubusercontent.com/59372326/207653767-4f83d575-f58d-4e2c-900f-de7cb9cb70f9.png)

## Proposed Changes

  - Now, in the `New Board `page the user can select one of two options
  - If he selects the SPLIT retro option, is redirected to the `NewSplitBoard` page, which contains the old content of the New  Board page.
  - If he selects the Regular retro, is redirected to the `NewRegularBoard` page, where he can select on of the two options.

This pull request closes #675

2022-12-14 19:52 UTC, nunocaseiro requested changes
Amazing job 🚀

2022-12-14 19:52 UTC, nunocaseiro commented on frontend/src/components/CreateBoard/SelectBoardType/BoxRowContainer/styles.tsx
> +  },
I think the background colour black is missed when the user hovers the box. The opposite of the text colour

2022-12-14 19:52 UTC, nunocaseiro commented on frontend/src/pages/boards/newSplitBoard.tsx
> +  } = useTeam({ autoFetchTeam: false });
Here we need to discuss if it makes sense to fetch all the teams or only those the user can create a split board. this means if the user is a team admin or stakeholder

2022-12-14 21:10 UTC, CatiaAntunes96 commented on frontend/src/pages/boards/newSplitBoard.tsx
> +  } = useTeam({ autoFetchTeam: false });
This condition will be dealt with in issue #677, in which you can only create team boards if the user is a team admin or team stakeholder. However, if the user is super admin, he should be able to create a board from any team right? This situation is not contemplated in the design.

2022-12-15 10:20 UTC, nunocaseiro approved these changes
LGTM :rocket:

2022-12-15 10:21 UTC, merged