feat: users lazy loading backend
xgeekshq/split pull request #682
Opened 2022-12-14 17:41 UTC by RafaelSBatista97

#594 

Relates to #602 

## Screenshots (if visual changes)

![image](https://user-images.githubusercontent.com/118206043/207667457-43958fbf-48e2-42d5-9b95-a14add05fb87.png)

![image](https://user-images.githubusercontent.com/118206043/207667539-0fe9dfdf-039a-406f-97b8-8e2e00b47329.png)

## Proposed Changes

-A lazy loading strategy should be implemented to avoid fetching all the platform users at the same time. So the user can fetch, for example, 15 at a time and more 15 when the scroll reaches its end.

Mention people who discussed this issue previously
@GuiSanto 

This pull request closes #602

2022-12-14 19:39 UTC, nunocaseiro requested changes

2022-12-14 19:39 UTC, nunocaseiro commented on backend/src/modules/teams/repositories/team-user.repository.ts
> +						pipeline: [{ $sort: { firstName: 1 } }]
```suggestion
```

2022-12-14 19:39 UTC, nunocaseiro commented on backend/src/modules/teams/repositories/team-user.repository.ts
> +
```suggestion
```

2022-12-14 19:39 UTC, nunocaseiro commented on backend/src/modules/users/repository/user.repository.ts
> +			.sort({ firstName: 1 })
You are sorting here only by the first name but in the other method you are sorting by first or last name. Please check if this won't be a problem :)

2022-12-14 20:34 UTC, rpvsilva requested changes

2022-12-14 20:34 UTC, rpvsilva commented on backend/src/modules/users/services/get.user.service.ts
> +			}
```suggestion
			}
			return a.user.firstName < b.user.firstName ? -1 : 1;
```

2022-12-15 09:16 UTC, RafaelSBatista97 commented on backend/src/modules/users/repository/user.repository.ts
> +			.sort({ firstName: 1 })
maybe this can be removed because we are sorting every user on the other method?

2022-12-15 09:21 UTC, nunocaseiro commented on backend/src/modules/users/repository/user.repository.ts
> +			.sort({ firstName: 1 })
The sort should also be here but make sure this Will work in every case

2022-12-15 10:08 UTC, rpvsilva approved these changes

2022-12-15 11:48 UTC, nunocaseiro approved these changes
LGTM 🚀

2022-12-15 11:52 UTC, merged