feat: backend done for search user
xgeekshq/split pull request #705
Opened 2022-12-16 17:27 UTC by GuiSanto

Relates to #594 

## Proposed Changes

  - backend receives a filter that will return users that contain that string in the firstname, lastname and email

This pull request closes #601

2022-12-16 17:36 UTC, nunocaseiro requested changes

2022-12-16 17:36 UTC, nunocaseiro commented on backend/src/modules/users/repository/user.repository.ts
> +
```suggestion
	getAllWithPagination(page: number, size: number, searchUser?: string) {
		let query: FilterQuery<UserDocument>;

		if (searchUser) {
			query = {
				$or: [
					{ firstName: { $regex: new RegExp('^.*' + searchUser + '.*$'), $options: 'i' } },
					{ lastName: { $regex: new RegExp('^.*' + searchUser + '.*$'), $options: 'i' } },
					{ email: { $regex: new RegExp('^.*' + searchUser + '.*$'), $options: 'i' } }
				]
			};
		}

		return this.model
			.find(query)
			.skip(page * size)
			.limit(size)
			.sort({ firstName: 1, lastName: 1 })
			.exec();
	}
```

I think this works and you can reuse some code

2022-12-16 18:13 UTC, rpvsilva approved these changes
LGTM 🔥

2022-12-19 10:36 UTC, nunocaseiro approved these changes
LGTM 🚀

2022-12-19 10:36 UTC, merged