fix: users edit teams list and delete users
xgeekshq/split pull request #735
Opened 2022-12-22 15:44 UTC by RafaelSBatista97

#733 and #732 

Relates to #594 

## Screenshots (if visual changes)

## Proposed Changes

  - We get an error from the backend when deleting a user. It doesn't delete. The error was when deleting a user with no teams it tried to delete and was giving an error because there was no verification if the user had team. (#733)
  - The other problem of (#732) was solved by using atoms.

@GuiSanto 

This pull request closes #733 and #732

2022-12-22 16:39 UTC, rpvsilva approved these changes
Just a small question. LGTM 🔥

2022-12-22 16:39 UTC, rpvsilva commented on backend/src/modules/users/services/delete.user.service.ts
> +			const userFound = await this.getTeamUserService.getTeamsOfUser(userId);
If you are getting the user teams, does it make sense that the variable is called `userFound`? The method returns the teams of the user right?

2022-12-22 16:52 UTC, nunocaseiro requested changes

2022-12-22 16:52 UTC, nunocaseiro commented on frontend/src/pages/users/[userId].tsx
>        setToastState({
Why are you disabling this? You can also use the custom hook `useTeam` that already has this method

2022-12-23 10:37 UTC, RafaelSBatista97 commented on frontend/src/pages/users/[userId].tsx
>        setToastState({
Because when its true it give an erro, dunno why :
![image](https://user-images.githubusercontent.com/118206043/209321444-e09fe244-dc6b-4323-87e5-31932bdffe87.png)

![image](https://user-images.githubusercontent.com/118206043/209321344-efb0315e-9e42-481c-9bf7-bdc7ff765aed.png)

2022-12-23 10:46 UTC, nunocaseiro commented on frontend/src/pages/users/[userId].tsx
>        setToastState({
It happens because you aren't sending the userId to the request

2022-12-23 10:46 UTC, nunocaseiro commented on frontend/src/pages/users/[userId].tsx
>        setToastState({
As you can see in the request url, the userId is undefined

2022-12-23 14:42 UTC, rpvsilva requested changes

2022-12-23 14:42 UTC, rpvsilva commented on frontend/src/components/Teams/TeamsList/partials/CardTeam/DeleteTeam.tsx
> +  const { deleteTeamUser } = useTeam({ autoFetchTeam: false });
```suggestion
  const { deleteTeam, deleteTeamUser } = useTeam({ autoFetchTeam: false });
```

2022-12-23 14:42 UTC, rpvsilva commented on frontend/src/components/Users/UsersList/partials/CardUser/CardBody.tsx
> +                href={`/users/${userWithTeams.user._id}?firstName=${userWithTeams.user.firstName}&lastName=${userWithTeams.user.lastName}&isSAdmin=${userWithTeams.user.isSAdmin}`}
There urls must be in a separate file, if you need to change one URL you need to change multiple components and search for them, you need to have a file of URLs and you get it from there.

2022-12-23 14:42 UTC, rpvsilva commented on frontend/src/components/Teams/TeamsList/partials/CardTeam/DeleteTeam.tsx
> +  const { deleteTeamUser } = useTeam({ autoFetchTeam: false });
Also you don't need to pass the variable as `false` since it's the default value

2022-12-23 14:42 UTC, rpvsilva commented on frontend/src/hooks/useTeamUtils.tsx
> +  if (session) loggedUserId = session.user.id;
You can do it like:
```javascript
const loggedUserId = session?.user.id || '';
```

2022-12-23 14:42 UTC, rpvsilva commented on frontend/src/pages/boards/index.tsx
> +  } = useTeam({ autoFetchTeamsOfUser: false });
Same as above, this is the default value

2022-12-23 15:27 UTC, nunocaseiro requested changes

2022-12-23 15:27 UTC, nunocaseiro commented on backend/src/modules/teams/services/delete.team.user.service.ts
> +		return deletedCount;
I think this can change with the changes I am requesting

2022-12-23 15:27 UTC, nunocaseiro commented on frontend/src/api/teamService.tsx
> +  fetchData(`/teams/${teamOfUserToDelete.userId}/${teamOfUserToDelete.teamId}`, {
```suggestion
  fetchData(`/teams/${teamOfUserToDelete.teamId}/users/${teamOfUserToDelete.teamUserId}`, {
```

2022-12-23 15:27 UTC, nunocaseiro commented on frontend/src/components/Teams/TeamsList/partials/CardTeam/CardBody.tsx
>              userId={userId}
```suggestion
            teamUserId={userFound?._id}
```

2022-12-23 15:27 UTC, nunocaseiro commented on frontend/src/components/Teams/TeamsList/partials/CardTeam/CardEnd.tsx
> +  userId?: string;
```suggestion
  teamUserId?: string;
```

2022-12-23 15:27 UTC, nunocaseiro commented on frontend/src/components/Teams/TeamsList/partials/CardTeam/CardEnd.tsx
> +            <DeleteTeam teamName={name} teamId={team._id} userId={userId} isTeamPage={isTeamPage} />
```suggestion
            <DeleteTeam teamName={name} teamId={team._id} teamUserId={teamUserId} isTeamPage={isTeamPage} />
```

2022-12-23 15:27 UTC, nunocaseiro commented on frontend/src/components/Teams/TeamsList/partials/CardTeam/CardEnd.tsx
> +  ({ team, havePermissions, userId, userSAdmin = undefined, isTeamPage }) => {
```suggestion
  ({ team, havePermissions, teamUserId, userSAdmin = undefined, isTeamPage }) => {
```

2022-12-23 15:27 UTC, nunocaseiro commented on frontend/src/components/Users/UserEdit/partials/UserHeader/index.tsx
> +  isSAdmin: string | string[] | undefined;
```suggestion
  firstName: string;
  lastName: string;
  isSAdmin: boolean;
```

2022-12-23 15:27 UTC, nunocaseiro commented on frontend/src/components/Users/UserEdit/partials/UserHeader/index.tsx
> +          {isSAdmin === 'true' && (
```suggestion
          {isSAdmin && (
```

2022-12-23 15:27 UTC, nunocaseiro commented on frontend/src/pages/boards/newRegularBoard.tsx
> +  } = useTeam({ autoFetchTeamsOfUser: false });
```suggestion
  } = useTeam();
```

2022-12-23 15:27 UTC, nunocaseiro commented on frontend/src/pages/boards/newRegularBoard.tsx
> +  } = useTeam({ autoFetchAllTeams: false });
```suggestion
  } = useTeam();
```

2022-12-23 15:27 UTC, nunocaseiro commented on frontend/src/pages/boards/newSplitBoard.tsx
> +  } = useTeam({ autoFetchTeamsOfUser: false });
```suggestion
  } = useTeam();
```

2022-12-23 15:27 UTC, nunocaseiro commented on frontend/src/pages/boards/newSplitBoard.tsx
> +  } = useTeam({ autoFetchAllTeams: false });
```suggestion
  } = useTeam();
```

2022-12-23 15:27 UTC, nunocaseiro commented on frontend/src/pages/teams/index.tsx
> +  } = useTeam({ autoFetchTeamsOfUser: false });
```suggestion
  } = useTeam();
```

2022-12-23 15:29 UTC, nunocaseiro requested changes

2022-12-23 15:29 UTC, nunocaseiro commented on frontend/src/components/CreateBoard/SplitBoard/SubTeamsTab/TeamSubTeamsConfigurations.tsx
> +    } = useTeam({ autoFetchTeamsOfUser: false });
```suggestion
    } = useTeam();
```

2022-12-23 16:31 UTC, RafaelSBatista97 commented on frontend/src/pages/boards/newRegularBoard.tsx
> +  } = useTeam({ autoFetchTeamsOfUser: false });
But if we take the "{ }" it outputs this error:
![image](https://user-images.githubusercontent.com/118206043/209368166-28d2e00f-e92d-48e9-9f95-905849567649.png)

2022-12-23 16:39 UTC, RafaelSBatista97 commented on frontend/src/components/Users/UserEdit/partials/UserHeader/index.tsx
> +  isSAdmin: string | string[] | undefined;
It needs these types because router.quey returns these types. Maybe we can check if it can be resolve by using joi validator, if you want.

![image](https://user-images.githubusercontent.com/118206043/209368508-6b8d6205-2f4b-45ad-8dba-f875257e32cf.png)

2022-12-23 19:33 UTC, rpvsilva approved these changes

2022-12-23 23:32 UTC, nunocaseiro approved these changes
LGTM 🚀

2022-12-26 09:39 UTC, merged