feat: add select team to regular board
xgeekshq/split pull request #736
Opened 2022-12-22 17:46 UTC by CatiaAntunes96

Relates to #677 

## Screenshots (if visual changes)
![image](https://user-images.githubusercontent.com/59372326/209194325-8ba49f85-e884-4043-b1c7-495e7421f49f.png)

## Proposed Changes

- Add a select with the teams in which the user is the team admin or stakeholder. If you are a superAdmin, you have access to all teams.
- The stateCreateBoard (atom that saves the board being created already saves the team, if it is selected and does not divide by sub-boards)
 

This pull request closes #677

2022-12-23 09:55 UTC, rpvsilva requested changes

2022-12-23 09:55 UTC, rpvsilva commented on frontend/src/pages/boards/newRegularBoard.tsx
> +    // }
And this?

2022-12-23 09:55 UTC, rpvsilva commented on frontend/src/pages/boards/newRegularBoard.tsx
> +  // };
Also this?

2022-12-23 09:55 UTC, rpvsilva commented on frontend/src/pages/boards/newRegularBoard.tsx
> +                  // })}
Also this?

2022-12-23 10:34 UTC, nunocaseiro commented on frontend/src/components/CreateBoard/RegularBoard/SettingsTabs/index.tsx
>        {/* {currentTab === 2 && <BoardConfigurations />} */}
I think it will be used in the next feature. same thing for the other comments

2022-12-23 10:37 UTC, rpvsilva commented on frontend/src/components/CreateBoard/RegularBoard/SettingsTabs/index.tsx
>        {/* {currentTab === 2 && <BoardConfigurations />} */}
Hmm ok, then I Catia can set them as resolved

2022-12-23 12:20 UTC, nunocaseiro approved these changes
LGTM 🚀

2023-01-02 09:57 UTC, rpvsilva approved these changes

2023-01-02 09:58 UTC, merged