fix: new board shows team selected on 1st render
xgeekshq/split pull request #746
Opened 2022-12-26 11:28 UTC by patricia-mdias

Fixes #745 

## Proposed Changes

  - New board shows team on 1st render when user clicks on "Create first team board" of a team.

This pull request closes #745

2022-12-26 14:19 UTC, nunocaseiro requested changes

2022-12-26 14:19 UTC, nunocaseiro commented on frontend/src/pages/boards/newSplitBoard.tsx
> +  }
This code will be executed in every render. can you move this to an useEffect ?

2022-12-27 09:49 UTC, patricia-mdias commented on frontend/src/pages/boards/newSplitBoard.tsx
> +  }
If I move this code to an useEffect, the problem will still persist. Using useEffect, there's no team selected on the 1st render.

2022-12-27 12:06 UTC, nunocaseiro commented on frontend/src/pages/boards/newSplitBoard.tsx
> +  }
Wierd. But ok lets go on with this

2022-12-27 12:06 UTC, nunocaseiro approved these changes

2022-12-27 12:45 UTC, merged