838 bug team members list ordering
xgeekshq/split pull request #841
Opened 2023-01-10 12:15 UTC by StereoPT

Relates to #838 
Fixes #838 

## Screenshots

![image](https://user-images.githubusercontent.com/8330038/211548145-73b8f722-24d8-4868-a0bc-fd3d5686c37e.png)

## Proposed Changes

  - The ListMembersDialog is now an independent component, it doesn't matter how he gets the users.
  - The component will sort the list it receives by:
    - Alphabetically
    - By Checked
    - Team Admin always on the first position 
  - getAllUsers from Backend will return an ordered list of users.

This pull request closes #838

2023-01-10 12:19 UTC, nunocaseiro requested changes

2023-01-10 12:19 UTC, nunocaseiro commented on backend/src/modules/users/utils/sortings.ts
> +};
This should be sorted in the query using the mongoose sort method

2023-01-10 12:19 UTC, nunocaseiro commented on backend/src/modules/users/services/get.user.service.ts
> +		});
The sort should be done in this query using the mongoose `sort` method.

[https://mongoosejs.com/docs/api/query.html#query_Query-sort](https://mongoosejs.com/docs/api/query.html#query_Query-sort)

2023-01-10 12:36 UTC, StereoPT commented on backend/src/modules/users/utils/sortings.ts
> +};
We were reusing a method that was already being used.

2023-01-10 15:18 UTC, rpvsilva requested changes

2023-01-10 15:18 UTC, rpvsilva commented on backend/src/modules/users/services/get.user.service.ts
> +		return allUsers;
```suggestion
	getAllUsers() {
		return this.userRepository.findAll(
			{
				password: 0,
				currentHashedRefreshToken: 0
			},
			{ firstName: 'asc', lastName: 'asc' }
		);
```

2023-01-10 15:18 UTC, rpvsilva commented on backend/src/modules/users/services/get.user.service.ts
> +		results.userWithTeams.sort((a, b) => sortAlphabetically(a.user, b.user));
Now you can remove this, right?

2023-01-10 15:18 UTC, rpvsilva commented on backend/src/modules/users/utils/sortings.ts
> +};
Also this

2023-01-10 15:51 UTC, StereoPT commented on backend/src/modules/users/services/get.user.service.ts
> +		results.userWithTeams.sort((a, b) => sortAlphabetically(a.user, b.user));
No, that needs to stay, because it's not an operation on the database, but on a joined array.

2023-01-10 16:14 UTC, rpvsilva submitted a review, later dismissed

2023-01-10 22:13 UTC, nunocaseiro requested changes

2023-01-10 22:13 UTC, nunocaseiro commented on backend/src/modules/users/services/get.user.service.ts
> +		);
```suggestion
 getAllUsers() {
		return this.userRepository.findAll(
			{
				password: 0,
				currentHashedRefreshToken: 0
			},
			{ firstName: 'asc', lastName: 'asc' }
		);
```

2023-01-11 10:40 UTC, rpvsilva approved these changes

2023-01-11 10:53 UTC, nunocaseiro approved these changes

2023-01-11 10:54 UTC, merged

2023-01-11 10:55 UTC, nunocaseiro commented
@all-contributors please add @StereoPT for code and doces

2023-01-11 10:56 UTC, nunocaseiro commented
@all-contributors please add @JoaoSaIvador for code and docs