bug: regular board update board name
xgeekshq/split pull request #879
Opened 2023-01-16 17:11 UTC by patricia-mdias

Fixes #871 

## Proposed Changes

  - Fix edit Regular Board name.
  - Use Board Guards to check permission of user.

This pull request closes #871

2023-01-16 19:09 UTC, nunocaseiro commented
I think the responsible guard isn't allowing a team admin or stakeholder to update a sub-board

2023-01-16 21:20 UTC, nunocaseiro requested changes

2023-01-17 11:23 UTC, patricia-mdias commented on backend/src/modules/boards/services/update.board.service.ts
> +		}
Done 🙂

2023-01-17 15:56 UTC, nunocaseiro approved these changes

2023-01-17 16:29 UTC, merged