feat: column operations actions
xgeekshq/split pull request #891
Opened 2023-01-17 16:49 UTC by CatiaAntunes96

Relates to #881 

## Proposed Changes

  -On the backend add updateColumn function, to update title, color and text card on a column

2023-01-17 20:45 UTC, rpvsilva requested changes

2023-01-17 20:45 UTC, rpvsilva commented on backend/src/modules/boards/controller/boards.controller.ts
> +		return board;
You should not do this kind of logic on controller side

2023-01-17 20:45 UTC, rpvsilva commented on backend/src/modules/boards/services/update.board.service.ts
> +	}
```suggestion
	updateColumn(boardId: string, column: UpdateColumnDto) {
		return this.boardModel
			.findOneAndUpdate(
				{
					_id: boardId,
					'columns._id': column._id
				},
				{
					$set: {
						'columns.$[column].color': column.color,
						'columns.$[column].title': column.title,
						'columns.$[column].cardText': column.cardText
					}
				},
				{
					arrayFilters: [{ 'column._id': column._id }],
					new: true
				}
			)
			.populate(BoardDataPopulate)
			.lean()
			.exec();
	}
```

2023-01-17 20:45 UTC, rpvsilva commented on backend/src/modules/boards/services/update.board.service.ts
> +	}
```suggestion
	emptyColumn(boardId: string, columnId: string) {
		return this.boardModel
			.find({
				_id: boardId,
				'columns._id': columnId
			})
			.populate(BoardDataPopulate)
			.lean()
			.exec();
	}
```

2023-01-19 11:50 UTC, nunocaseiro approved these changes

2023-01-19 11:50 UTC, nunocaseiro commented on backend/src/modules/boards/controller/boards.controller.ts
> +	@Put(':boardId/column')
```suggestion
	@Put(':boardId/column/:columnId')
```
I know you are sending the columnId in the dto but I think the columnId should be included in the route as I'm not mistaken it is a best practice

2023-01-19 16:52 UTC, nunocaseiro approved these changes

2023-01-20 11:03 UTC, rpvsilva approved these changes
LGTM 🔥

2023-01-20 11:04 UTC, merged